package software.sava.core.tx;

import org.junit.jupiter.api.Test;
import software.sava.core.accounts.PublicKey;
import software.sava.core.accounts.Signer;
import software.sava.core.accounts.meta.AccountMeta;
import software.sava.core.encoding.Base58;
import software.sava.core.encoding.ByteUtil;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Base64;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.TreeSet;

import static org.junit.jupiter.api.Assertions.*;
import static software.sava.core.tx.V1TransactionSkeleton.ACCOUNT_DATA_SIZE_LIMIT_MASK;
import static software.sava.core.tx.V1TransactionSkeleton.COMPUTE_UNIT_LIMIT_MASK;
import static software.sava.core.tx.V1TransactionSkeleton.HEAP_SIZE_MASK;
import static software.sava.core.tx.V1TransactionSkeleton.PRIORITY_FEE_MASK;

/// Builder-side external oracle for Sava's SIMD-0385 transaction v1 support: the committed fixture is
/// generated by `@solana/kit` 8.0.0 — the maintained TypeScript implementation — driven by the locked
/// generator in `src/test/solana/kit-v1-vectors`. Normal Java tests need neither Node nor network
/// access; Gradle only reads the TSV.
///
/// The sibling [V1MessageConformanceTests] fixture is produced by a Rust program Sava's authors wrote
/// against `solana-message`, so a misreading of the SIMD shared between that program and Sava's
/// builder would agree with itself. Kit's compiler, signer, and decoders share no code and no author
/// with either, and every byte in this fixture comes from kit: the unsigned message from
/// `compileTransaction`, the signed wire from `signTransactionMessageWithSigners`, and the read-back
/// columns from kit's own decoders. Sava contributes nothing at generation time.
///
/// Three directions are pinned. Build: [TxBuilder] with the seeded signers reproduces kit's bytes
/// byte-for-byte for every vector it can express. Read: [TransactionSkeleton#deserializeSkeleton]
/// reports what kit says it wrote, including the `TransactionConfigMask` bits an explicit zero keeps.
/// Sign: re-signing kit's zeroed signature block reproduces kit's ed25519 signatures in kit's slots.
/// The fourth direction — kit decoding Sava's bytes — was verified once by the spike's `decode.ts`
/// and is deliberately not part of Gradle; see the generator README.
///
/// Two vectors are exceptions the fixture exists to make explicit. `e_explicit_zeros` is a shape
/// [TxBuilder] cannot emit (an explicit 0 clears the mask bit), pinned by
/// [#builderCannotEmitKitsExplicitZeroConfigValues]; `i_two_readonly_programs` puts three accounts in
/// one role, where kit's collation order and Sava's unspecified order may legitimately differ, pinned
/// as canonical equivalence by [#builderAgreesWithKitUpToSameRoleOrderOnTwoReadonlyPrograms].
final class KitV1VectorTests {

  private static final String RESOURCE = "/tx/kit-v1-message-vectors.tsv";
  private static final String GENERATOR = "src/test/solana/kit-v1-vectors";
  private static final String COLUMNS =
      "id\tconfig\textra\tconfig_mask\theader\tstatic_accounts\tprogram_ids\tinstruction_data_hex\t"
          + "unsigned_message_hex\tsigned_wire_hex\tsignatures_hex\tread_back_version\tread_back_config";
  /// The fixture's vectors, in order. Pinned by name so a row cannot be dropped, duplicated or
  /// renamed without this list changing: a count alone would stay green if `f_two_signers` were
  /// replaced by a second copy of a single-signer row, silently losing two-signature coverage.
  private static final List<String> EXPECTED_IDS = List.of(
      "a_example_config",
      "b_empty_config",
      "c_only_cu_limit",
      "d_only_priority_fee",
      "e_explicit_zeros",
      "f_two_signers",
      "g_large_memo",
      "h_sava_defaults",
      "i_two_readonly_programs"
  );
  private static final int VECTOR_COUNT = EXPECTED_IDS.size();
  private static final HexFormat HEX = HexFormat.of();
  private static final int MISMATCH_CONTEXT = 32;

  private static final String EXPLICIT_ZEROS_VECTOR = "e_explicit_zeros";
  private static final String SAVA_DEFAULTS_VECTOR = "h_sava_defaults";
  private static final String TIE_BREAK_VECTOR = "i_two_readonly_programs";

  private static final PublicKey SYSTEM_PROGRAM = PublicKey.fromBase58Encoded("11111111111111111111111111111111");
  private static final PublicKey MEMO_PROGRAM = PublicKey.fromBase58Encoded("MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr");
  private static final PublicKey ED25519_PROGRAM = PublicKey.fromBase58Encoded("Ed25519SigVerify111111111111111111111111111");
  private static final int SYSTEM_TRANSFER_DISCRIMINATOR = 2;
  private static final long TRANSFER_LAMPORTS = 1L;

  private static final byte[] PAYER_SEED = seed(0x01);
  private static final byte[] RECIPIENT_SEED = seed(0x02);
  private static final byte[] SECOND_SEED = seed(0x03);
  private static final byte[] BLOCKHASH = seed(0x04);
  private static final Signer PAYER = Signer.createFromPrivateKey(PAYER_SEED);
  private static final Signer RECIPIENT = Signer.createFromPrivateKey(RECIPIENT_SEED);
  private static final Signer SECOND = Signer.createFromPrivateKey(SECOND_SEED);
  private static final Map<String, Signer> SIGNERS_BY_ADDRESS = Map.of(
      PAYER.publicKey().toBase58(), PAYER,
      RECIPIENT.publicKey().toBase58(), RECIPIENT,
      SECOND.publicKey().toBase58(), SECOND
  );

  private static final Map<String, String> EXPECTED_METADATA = Map.ofEntries(
      Map.entry("format", "sava-kit-v1-message-v1"),
      Map.entry(
          "property",
          "Sava's transaction v1 builder, signer, and reader agree with @solana/kit's compiler, signer, "
              + "and decoders on SIMD-0385 wire bytes"
      ),
      Map.entry("simd", "0385-transaction-v1"),
      Map.entry("@solana/kit", "8.0.0"),
      Map.entry("@solana-program/system", "0.13.0"),
      Map.entry("@solana-program/memo", "0.13.0"),
      Map.entry("tsx", "4.23.12"),
      Map.entry("node", "v26.7.0"),
      Map.entry("payer-seed-hex", "0101010101010101010101010101010101010101010101010101010101010101"),
      Map.entry("recipient-seed-hex", "0202020202020202020202020202020202020202020202020202020202020202"),
      Map.entry("second-seed-hex", "0303030303030303030303030303030303030303030303030303030303030303"),
      Map.entry("blockhash-hex", "0404040404040404040404040404040404040404040404040404040404040404"),
      Map.entry("payer-address", "AKnL4NNf3DGWZJS6cPknBuEGnVsV4A4m5tgebLHaRSZ9"),
      Map.entry("recipient-address", "9hSR6S7WPtxmTojgo6GG3k4yDPecgJY292j7xrsUGWBu"),
      Map.entry("second-address", "GyGKxMyg1p9SsHfm15MkNUu1u9TN2JtTspcdmrtGUdse"),
      Map.entry("blockhash-base58", "GgBaCs3NCBuZN12kCJgAW63ydqohFkHEdfdEXBPzLHq"),
      Map.entry(
          "same-role-ordering",
          "kit sorts same-role accounts by Intl.Collator(en) over base58; Sava leaves them unordered"
      ),
      Map.entry("package-json-sha256", "15ff053938b8d269a3183d14378a45c90c3ea069c3f73c8bd7092502321bbad6"),
      Map.entry("pnpm-lock-sha256", "a075aa449d5d4f42581da8202e192c28a0be0c9a75543dc00ab06ba80abacd78"),
      Map.entry("pnpm-workspace-sha256", "43ec7f44d6604a53db59c5a093e87a4916becfbb9baba7fb3582594cb32f9e44"),
      Map.entry("generator-source-sha256", "936427a9d30cba3e7e8c860ff339c3d06507987fc381e7e71e9cdc580fedca42"),
      Map.entry("vectors", Integer.toString(VECTOR_COUNT))
  );

  /// The fixture records the sha256 of every generator input, so an edited generator, a changed
  /// dependency pin, or a re-resolved lockfile fails here until the fixture is regenerated and this
  /// class's expected provenance is updated alongside it.
  @Test
  void fixtureProvenanceMatchesCommittedGeneratorInputs() throws IOException {
    final var metadata = loadFixture().metadata();
    assertFileSha256(metadata, "package-json-sha256", "package.json");
    assertFileSha256(metadata, "pnpm-lock-sha256", "pnpm-lock.yaml");
    assertFileSha256(metadata, "pnpm-workspace-sha256", "pnpm-workspace.yaml");
    assertFileSha256(metadata, "generator-source-sha256", "gen.ts");
  }

  /// Everything downstream signs and compares against these keys, so the derivation is pinned first:
  /// [Signer#createFromPrivateKey] over the recorded 32-byte seeds must produce the addresses kit
  /// derived from the same seeds, and the recorded blockhash must be the base58 of 32 x 0x04. A
  /// mismatch here means the byte comparisons below would fail for a reason unrelated to the wire
  /// format.
  @Test
  void seededKeysDeriveKitsAddresses() throws IOException {
    final var fixture = loadFixture();
    final var metadata = fixture.metadata();
    assertArrayEquals(PAYER_SEED, HEX.parseHex(metadata.get("payer-seed-hex")), "payer seed");
    assertArrayEquals(RECIPIENT_SEED, HEX.parseHex(metadata.get("recipient-seed-hex")), "recipient seed");
    assertArrayEquals(SECOND_SEED, HEX.parseHex(metadata.get("second-seed-hex")), "second seed");
    assertArrayEquals(BLOCKHASH, HEX.parseHex(metadata.get("blockhash-hex")), "blockhash");
    assertEquals(metadata.get("payer-address"), PAYER.publicKey().toBase58(), "payer key derivation");
    assertEquals(metadata.get("recipient-address"), RECIPIENT.publicKey().toBase58(), "recipient key derivation");
    assertEquals(metadata.get("second-address"), SECOND.publicKey().toBase58(), "second key derivation");
    assertEquals(metadata.get("blockhash-base58"), Base58.encode(BLOCKHASH), "blockhash base58");

    // Every vector is paid for by the seeded payer, and every signer is one of the seeded keys.
    for (final var vector : fixture.vectors()) {
      assertEquals(PAYER.publicKey().toBase58(), vector.staticAccounts().getFirst(), vector.id() + " fee payer");
      for (final var signer : vector.signerAddresses()) {
        assertTrue(SIGNERS_BY_ADDRESS.containsKey(signer), () -> vector.id() + " unknown signer " + signer);
      }
    }
  }

  /// The byte-for-byte builder pin. For every vector [TxBuilder] can express, the seeded fee payer,
  /// the same instructions, the same config values, and the fixed blockhash must reproduce kit's
  /// unsigned message and kit's signed wire exactly: version prefix, header, mask, ConfigValues
  /// widths and order, account order, instruction headers and payloads, and the trailing signature
  /// block. Absent config fields are cleared with 0 rather than left at the builder's defaults, so
  /// the defaults are exercised separately by [#builderDefaultsMatchKitsExplicitSavaDefaultsVector].
  ///
  /// A mismatch reports the first differing offset with 32 bytes of context from each side, which is
  /// enough to tell a framing error from a config-width error from an account-order difference.
  @Test
  void builderReproducesKitBytesForEveryProducibleVector() throws IOException {
    int checked = 0;
    for (final var vector : loadFixture().vectors()) {
      if (!vector.builderProducible() || vector.id().equals(TIE_BREAK_VECTOR)) {
        continue;
      }
      ++checked;
      assertSavaBytesEqualKit(vector, build(vector, configuredBuilder(vector)));
    }
    assertEquals(VECTOR_COUNT - 2, checked, "builder-producible vectors");
  }

  /// `h_sava_defaults` is kit asked for exactly what [TxBuilder] serializes when nothing is set: a
  /// 1_400_000 compute-unit limit and a 64MiB loaded-accounts-data-size limit, no fee, no heap. A bare
  /// builder must therefore match it byte-for-byte. This is the external pin on the deliberate
  /// divergence recorded in AGAVE_SYNC.md — the defaults reserve both slots for in-place updates —
  /// and it fails the day the defaults change without this vector being regenerated.
  @Test
  void builderDefaultsMatchKitsExplicitSavaDefaultsVector() throws IOException {
    final var vector = vector(loadFixture().vectors(), SAVA_DEFAULTS_VECTOR);
    assertEquals("-:1400000:67108864:-", vector.configText(), "vector requests the builder defaults explicitly");
    assertEquals(COMPUTE_UNIT_LIMIT_MASK | ACCOUNT_DATA_SIZE_LIMIT_MASK, vector.configMask());
    assertSavaBytesEqualKit(vector, build(vector, TxBuilder.createBuilder().feePayer(PAYER.publicKey())));
  }

  /// Three read-only non-signer programs sit in one role. Kit orders same-role accounts with an
  /// `Intl.Collator("en")` comparison over their base58 text; Sava's `LEGACY_META_COMPARATOR`
  /// returns 0 for such ties, so their relative order is whatever the account map yields. Neither
  /// order is more correct — SIMD-0385 does not specify one — so byte equality is the wrong
  /// property here. What must hold is canonical equivalence: the same header, the same account set
  /// with the same roles, the same instructions once account indexes are resolved back to keys, the
  /// same signer keys, and a valid signature from each signer over whatever message Sava produced.
  /// Sava's reader resolves both sides; its agreement with kit's own columns is pinned separately by
  /// [#readerParsesKitWireAsKitDescribesIt].
  ///
  /// If the orders coincide, the bytes must coincide too, so a change to either side's ordering
  /// shows up here in one direction or the other rather than silently widening the gap. At the
  /// time of writing they do not coincide: kit compiles `1111…, Ed25519…, Memo…` and Sava's map
  /// yields `Ed25519…, 1111…, Memo…`, so this vector really does exercise the tie-break.
  @Test
  void builderAgreesWithKitUpToSameRoleOrderOnTwoReadonlyPrograms() throws IOException {
    final var vector = vector(loadFixture().vectors(), TIE_BREAK_VECTOR);
    assertEquals(3, vector.numReadonlyUnsigned(), "three read-only programs share a role");
    final var built = build(vector, configuredBuilder(vector));
    final var id = vector.id();

    final var kitSkeleton = TransactionSkeleton.deserializeSkeleton(vector.signedWire());
    final var savaSkeleton = TransactionSkeleton.deserializeSkeleton(built.signedWire());
    assertEquals(1, savaSkeleton.version(), id);
    assertEquals(vector.numSigners(), savaSkeleton.numSignatures(), id + " header signers");
    assertEquals(vector.numReadonlySigned(), savaSkeleton.numReadonlySignedAccounts(), id + " header readonly signed");
    assertEquals(vector.numReadonlyUnsigned(), savaSkeleton.numReadonlyUnsignedAccounts(), id + " header readonly unsigned");
    assertEquals(vector.staticAccounts().size(), savaSkeleton.numAccounts(), id + " account count");
    assertEquals(vector.unsignedMessage().length, built.unsignedMessage().length, id + " message length");
    assertEquals(vector.signedWire().length, built.signedWire().length, id + " wire length");
    assertEquals(vector.configMask(), assertInstanceOf(V1TransactionSkeleton.class, savaSkeleton).configMask(), id + " config mask");

    // Same accounts in the same roles, compared as a set.
    final var savaAccounts = savaSkeleton.parseAccounts();
    final var kitAccounts = kitSkeleton.parseAccounts();
    assertEquals(rolesByAddress(kitAccounts), rolesByAddress(savaAccounts), id + " account roles");
    assertEquals(new TreeSet<>(vector.staticAccounts()), new TreeSet<>(addresses(savaAccounts)), id + " account set");
    assertEquals(
        vector.signerAddresses(),
        Arrays.stream(savaSkeleton.parseSignerPublicKeys()).map(PublicKey::toBase58).toList(),
        id + " signer keys"
    );

    // Same instructions once indexes are resolved back to keys.
    final var kitInstructions = kitSkeleton.parseInstructions(kitAccounts);
    final var savaInstructions = savaSkeleton.parseInstructions(savaAccounts);
    assertEquals(vector.programIds().size(), savaInstructions.length, id + " instruction count");
    for (int index = 0; index < savaInstructions.length; ++index) {
      final var kit = kitInstructions[index];
      final var sava = savaInstructions[index];
      assertEquals(vector.programIds().get(index), sava.programId().publicKey().toBase58(), id + " program " + index);
      assertArrayEquals(vector.instructionData().get(index), sava.copyData(), id + " data " + index);
      assertEquals(addresses(kit.accounts()), addresses(sava.accounts()), id + " instruction " + index + " accounts");
    }

    // A valid signature from each signer over the message Sava actually produced.
    final int messageLength = built.unsignedMessage().length;
    final var signerKeys = savaSkeleton.parseSignerPublicKeys();
    for (int index = 0; index < signerKeys.length; ++index) {
      final byte[] signature = signatureSlot(built.signedWire(), messageLength, index);
      assertTrue(
          PublicKey.verifySignature(signerKeys[index].toByteArray(), 0, built.signedWire(), 0, messageLength, signature),
          id + " signature " + index + " verifies for " + signerKeys[index].toBase58()
      );
    }

    // When the orders coincide nothing else may differ.
    if (addresses(savaAccounts).equals(vector.staticAccounts())) {
      assertSavaBytesEqualKit(vector, built);
    }
  }

  /// The read-side pin, for every vector including the two the builder cannot reproduce. Sava's
  /// skeleton must report what kit says it wrote: version 1, each config value (0 when absent),
  /// the raw `TransactionConfigMask` — which is how an explicit zero is told apart from an absent
  /// field, since both read as 0 — the header counts, the blockhash, every static account in kit's
  /// order, the signer keys, every program id and instruction payload, and the implied boundary
  /// between message and signature block. Kit's read-back columns are its own decoders' view of the
  /// same bytes, and Sava must agree with those too.
  @Test
  void readerParsesKitWireAsKitDescribesIt() throws IOException {
    for (final var vector : loadFixture().vectors()) {
      final var id = vector.id();
      final byte[] wire = vector.signedWire();
      final var skeleton = assertInstanceOf(
          V1TransactionSkeleton.class,
          TransactionSkeleton.deserializeSkeleton(wire),
          id + " dispatches to the v1 skeleton"
      );
      assertEquals(1, skeleton.version(), id);
      assertEquals(vector.readBackVersion(), skeleton.version(), id + " kit read back the same version");
      assertTrue(skeleton.isVersioned(), id);
      assertFalse(skeleton.isLegacy(), id);

      assertEquals(vector.configMask(), skeleton.configMask(), id + " config mask");
      // Kit's decompiler reports a config object exactly when a mask bit is set — an all-zero
      // explicit config (e_explicit_zeros) is still "present", and a zero mask is "none".
      assertEquals(
          vector.readBackConfig().present(),
          skeleton.configMask() != 0,
          id + " kit reports a config object iff the mask is non-zero"
      );
      assertConfigMatches(id + " input", vector.config(), skeleton);
      assertConfigMatches(id + " kit read back", vector.readBackConfig(), skeleton);

      assertEquals(vector.numSigners(), skeleton.numSignatures(), id + " signatures");
      assertEquals(vector.numReadonlySigned(), skeleton.numReadonlySignedAccounts(), id + " readonly signed");
      assertEquals(vector.numReadonlyUnsigned(), skeleton.numReadonlyUnsignedAccounts(), id + " readonly unsigned");
      assertEquals(vector.staticAccounts().size(), skeleton.numAccounts(), id + " accounts");
      assertEquals(0, skeleton.numIndexedAccounts(), id + " no lookup table accounts");
      assertArrayEquals(BLOCKHASH, skeleton.blockHash(), id + " blockhash");
      assertEquals(vector.staticAccounts().getFirst(), skeleton.feePayer().toBase58(), id + " fee payer");

      final var accounts = skeleton.parseAccounts();
      assertEquals(vector.staticAccounts(), addresses(accounts), id + " static accounts in kit's order");
      assertEquals(
          vector.signerAddresses(),
          Arrays.stream(skeleton.parseSignerPublicKeys()).map(PublicKey::toBase58).toList(),
          id + " signer keys"
      );
      for (int index = 0; index < accounts.length; ++index) {
        assertEquals(vector.signer(index), accounts[index].signer(), id + " account " + index + " signer role");
        assertEquals(vector.writable(index), accounts[index].write(), id + " account " + index + " writable role");
      }

      assertEquals(vector.programIds().size(), skeleton.numInstructions(), id + " instruction count");
      final var instructions = skeleton.parseInstructions(accounts);
      assertEquals(vector.programIds().size(), instructions.length, id + " parsed instructions");
      for (int index = 0; index < instructions.length; ++index) {
        assertEquals(vector.programIds().get(index), instructions[index].programId().publicKey().toBase58(), id + " program " + index);
        assertArrayEquals(vector.instructionData().get(index), instructions[index].copyData(), id + " data " + index);
      }

      // The message ends where kit's unsigned message ends, and only the signature block follows.
      final int messageLength = vector.unsignedMessage().length;
      assertEquals(messageLength, V1TransactionSkeleton.messageEnd(wire), id + " message end");
      assertEquals(messageLength, V1TransactionSkeleton.requireSignatureBlockOffset(wire), id + " signature block offset");
      assertEquals(messageLength + (vector.numSigners() * Transaction.SIGNATURE_LENGTH), wire.length, id + " wire length");
      assertArrayEquals(vector.unsignedMessage(), Arrays.copyOf(wire, messageLength), id + " message bytes");
      for (int index = 0; index < vector.numSigners(); ++index) {
        assertArrayEquals(vector.signatures().get(index), signatureSlot(wire, messageLength, index), id + " signature slot " + index);
      }
      assertEquals(Base58.encode(vector.signatures().getFirst()), skeleton.id(), id + " transaction id");
    }
  }

  /// The signer pin, for every vector. Zero kit's signature block, parse the result, promote it to a
  /// mutable [Transaction], and sign with the seeded keys: the wire must come back equal to kit's,
  /// which requires Sava to sign exactly the bytes kit signed (the message including its 0x81
  /// prefix, nothing more) and to place each signature in kit's slot for that signer. Ed25519 is
  /// deterministic, so a single differing signed byte changes all 64 bytes of the signature.
  @Test
  void resigningKitMessageReproducesKitSignatures() throws IOException {
    for (final var vector : loadFixture().vectors()) {
      final var id = vector.id();
      final byte[] wire = vector.signedWire();
      final int messageLength = vector.unsignedMessage().length;
      final byte[] unsigned = wire.clone();
      Arrays.fill(unsigned, messageLength, unsigned.length, (byte) 0);

      final var transaction = TransactionSkeleton.deserializeSkeleton(unsigned).createTransaction();
      assertEquals(1, transaction.version(), id);
      assertEquals(vector.numSigners(), transaction.numSigners(), id + " signers");
      for (final var signer : signers(vector)) {
        transaction.sign(signer);
      }
      final byte[] resigned = transaction.serialized();
      assertSameBytes(id + " re-signed wire", wire, resigned);
      for (int index = 0; index < vector.numSigners(); ++index) {
        assertArrayEquals(
            vector.signatures().get(index),
            signatureSlot(resigned, messageLength, index),
            id + " signature " + index + " for " + vector.signerAddresses().get(index)
        );
      }
      assertEquals(Base58.encode(vector.signatures().getFirst()), transaction.getBase58Id(), id + " transaction id");
    }
  }

  /// `e_explicit_zeros` is the one shape kit can emit that [TxBuilder] cannot: kit keeps a field
  /// whose value is 0 in the mask and writes its zero ConfigValue, while the builder treats 0 as
  /// "clear this field" and drops the bit. Both are valid SIMD-0385 encodings and the runtime reads
  /// them identically, so the divergence is deliberate — but it must stay visible. This pins each
  /// half: kit's bytes carry mask `0b1111` over sixteen zero bytes and Sava reads them as such; a
  /// builder given the same zeros emits mask 0 and a message sixteen bytes shorter, and its in-place
  /// setters refuse the absent slots; and kit's explicit-zero shape, once parsed, is exactly the
  /// update-in-place shape whose slots the setters can fill. If the builder ever learns to emit
  /// explicit zeros, [#builderReproducesKitBytesForEveryProducibleVector] should take this vector
  /// over and this test should be retired with it.
  @Test
  void builderCannotEmitKitsExplicitZeroConfigValues() throws IOException {
    final var vector = vector(loadFixture().vectors(), EXPLICIT_ZEROS_VECTOR);
    assertEquals("0:0:0:-", vector.configText(), "kit was asked for explicit zeros and no heap");
    assertFalse(vector.builderProducible(), "the builder byte test skips this vector");
    final int explicitZeroMask = PRIORITY_FEE_MASK | COMPUTE_UNIT_LIMIT_MASK | ACCOUNT_DATA_SIZE_LIMIT_MASK;
    assertEquals(explicitZeroMask, vector.configMask(), "kit keeps the mask bits of explicit zeros");
    assertEquals(0, vector.configMask() & HEAP_SIZE_MASK, "the unset heap has no bit");

    // Kit's bytes: three set fields, all zero, occupying 8 + 4 + 4 bytes after the accounts.
    final byte[] wire = vector.signedWire();
    final var kitSkeleton = assertInstanceOf(V1TransactionSkeleton.class, TransactionSkeleton.deserializeSkeleton(wire));
    assertEquals(explicitZeroMask, kitSkeleton.configMask());
    assertEquals(0L, kitSkeleton.priorityFeeLamports());
    assertEquals(0, kitSkeleton.computeUnitLimit());
    assertEquals(0, kitSkeleton.accountDataSizeLimit());
    assertEquals(0, kitSkeleton.heapSize());
    final int configValuesOffset = V1TransactionSkeleton.V1_ACCOUNTS_OFFSET
        + (vector.staticAccounts().size() * PublicKey.PUBLIC_KEY_LENGTH);
    final int configValuesLength = Integer.bitCount(explicitZeroMask) << 2;
    assertEquals(16, configValuesLength);
    assertEquals(configValuesOffset + configValuesLength, kitSkeleton.instructionsOffset(), "instructions follow the zero ConfigValues");
    for (int offset = configValuesOffset; offset < configValuesOffset + configValuesLength; ++offset) {
      assertEquals(0, wire[offset], "explicit zero ConfigValue byte at " + offset);
    }

    // The builder: the same zeros clear every bit, and the message loses those sixteen bytes.
    final var builder = TxBuilder.createBuilder()
        .feePayer(PAYER.publicKey())
        .addInstructions(instructions(vector))
        .priorityFeeLamports(0L)
        .computeUnitLimit(0)
        .accountDataSizeLimit(0);
    final var built = builder.createTransaction();
    built.setRecentBlockHash(BLOCKHASH);
    final var savaSkeleton = assertInstanceOf(V1TransactionSkeleton.class, TransactionSkeleton.deserializeSkeleton(built.serialized()));
    assertEquals(0, savaSkeleton.configMask(), "an explicit 0 clears the builder's mask bit");
    assertEquals(0, savaSkeleton.configMask() & PRIORITY_FEE_MASK);
    assertEquals(0, savaSkeleton.configMask() & COMPUTE_UNIT_LIMIT_MASK);
    assertEquals(0, savaSkeleton.configMask() & ACCOUNT_DATA_SIZE_LIMIT_MASK);
    assertEquals(
        vector.unsignedMessage().length - configValuesLength,
        built.serialized().length - (vector.numSigners() * Transaction.SIGNATURE_LENGTH),
        "the builder's message is exactly the zero ConfigValues shorter"
    );
    assertThrows(IllegalStateException.class, () -> built.setPriorityFeeLamports(1L), "no priority fee slot to update");
    assertThrows(IllegalStateException.class, () -> built.setComputeUnitLimit(1), "no compute unit limit slot to update");
    assertThrows(IllegalStateException.class, () -> built.setAccountDataSizeLimit(1), "no data size slot to update");

    // Kit's shape, parsed by Sava, is the update-in-place shape the builder reserves with non-zero
    // defaults: every slot is present and the setters fill it without changing the mask or length.
    final byte[] unsigned = wire.clone();
    Arrays.fill(unsigned, vector.unsignedMessage().length, unsigned.length, (byte) 0);
    final var reserved = TransactionSkeleton.deserializeSkeleton(unsigned).createTransaction();
    reserved.setPriorityFeeLamports(5_000L);
    reserved.setComputeUnitLimit(20_000);
    reserved.setAccountDataSizeLimit(65_536);
    assertThrows(IllegalStateException.class, () -> reserved.setHeapSize(64 * 1_024), "the heap slot kit left absent stays absent");
    final var updated = assertInstanceOf(V1TransactionSkeleton.class, TransactionSkeleton.deserializeSkeleton(reserved.serialized()));
    assertEquals(explicitZeroMask, updated.configMask(), "in-place updates keep kit's mask");
    assertEquals(wire.length, reserved.serialized().length, "in-place updates keep kit's length");
    assertEquals(5_000L, updated.priorityFeeLamports());
    assertEquals(20_000, updated.computeUnitLimit());
    assertEquals(65_536, updated.accountDataSizeLimit());
    assertEquals(0, updated.heapSize());
  }

  private static TxBuilder configuredBuilder(final Vector vector) {
    final var config = vector.config();
    final var builder = TxBuilder.createBuilder()
        .feePayer(PAYER.publicKey())
        // 0 clears the builder's default for these two; an absent kit field is an absent slot.
        .computeUnitLimit(config.computeUnitLimitOrZero())
        .accountDataSizeLimit(config.accountDataSizeLimitOrZero());
    if (config.priorityFee() != null) {
      builder.priorityFeeLamports(config.priorityFee());
    }
    if (config.heapSize() != null) {
      builder.heapSize(config.heapSizeOrZero());
    }
    return builder;
  }

  /// Adds the vector's instructions to the builder, stamps the fixed blockhash, captures the message
  /// with an all-zero signature block, then signs with the vector's seeded signers.
  private static Built build(final Vector vector, final TxBuilder builder) {
    final var transaction = builder.addInstructions(instructions(vector)).createTransaction();
    transaction.setRecentBlockHash(BLOCKHASH);
    final byte[] unsigned = transaction.serialized().clone();
    final int messageLength = unsigned.length - (transaction.numSigners() * Transaction.SIGNATURE_LENGTH);
    for (int offset = messageLength; offset < unsigned.length; ++offset) {
      assertEquals(0, unsigned[offset], vector.id() + " unsigned signature block byte at " + offset);
    }
    for (final var signer : signers(vector)) {
      transaction.sign(signer);
    }
    return new Built(transaction, Arrays.copyOf(unsigned, messageLength), transaction.serialized());
  }

  private static void assertSavaBytesEqualKit(final Vector vector, final Built built) {
    final var id = vector.id();
    final var transaction = built.transaction();
    assertEquals(1, transaction.version(), id + " version");
    assertEquals(vector.numSigners(), transaction.numSigners(), id + " signers");
    assertSameBytes(id + " unsigned message", vector.unsignedMessage(), built.unsignedMessage());
    assertSameBytes(id + " signed wire", vector.signedWire(), built.signedWire());
    assertEquals(vector.signedWire().length, transaction.size(), id + " size");
    assertEquals(Base64.getEncoder().encodeToString(vector.signedWire()), transaction.base64EncodeToString(), id + " base64");
    assertEquals(Base58.encode(vector.signatures().getFirst()), transaction.getBase58Id(), id + " transaction id");
  }

  /// Fails with the first differing offset and up to 32 bytes of context from each side.
  private static void assertSameBytes(final String label, final byte[] kit, final byte[] sava) {
    final int diff = Arrays.mismatch(kit, sava);
    if (diff < 0) {
      return;
    }
    fail(String.format(
        "%s: first differing offset=%d (kit len=%d, sava len=%d)%n  kit [%d..+%d]=%s%n  sava[%d..+%d]=%s",
        label, diff, kit.length, sava.length,
        diff, MISMATCH_CONTEXT, context(kit, diff),
        diff, MISMATCH_CONTEXT, context(sava, diff)
    ));
  }

  private static String context(final byte[] bytes, final int from) {
    if (from >= bytes.length) {
      return "<end>";
    }
    return HEX.formatHex(bytes, from, Math.min(bytes.length, from + MISMATCH_CONTEXT));
  }

  private static byte[] signatureSlot(final byte[] wire, final int messageLength, final int index) {
    final int from = messageLength + (index * Transaction.SIGNATURE_LENGTH);
    return Arrays.copyOfRange(wire, from, from + Transaction.SIGNATURE_LENGTH);
  }

  private static void assertConfigMatches(final String label, final Config config, final V1TransactionSkeleton skeleton) {
    assertEquals(config.priorityFeeOrZero(), skeleton.priorityFeeLamports(), label + " priority fee");
    assertEquals(config.computeUnitLimitOrZero(), skeleton.computeUnitLimit(), label + " compute unit limit");
    assertEquals(config.accountDataSizeLimitOrZero(), skeleton.accountDataSizeLimit(), label + " account data size limit");
    assertEquals(config.heapSizeOrZero(), skeleton.heapSize(), label + " heap size");
  }

  private static List<Instruction> instructions(final Vector vector) {
    final var instructions = new ArrayList<Instruction>();
    instructions.add(transfer(PAYER.publicKey(), RECIPIENT.publicKey()));
    switch (vector.extra()) {
      case "none" -> {
      }
      case "second-signer" -> instructions.add(transfer(SECOND.publicKey(), RECIPIENT.publicKey()));
      case "memo" -> instructions.add(accountFree(vector, 1, MEMO_PROGRAM));
      case "memo+ed25519" -> {
        instructions.add(accountFree(vector, 1, MEMO_PROGRAM));
        instructions.add(accountFree(vector, 2, ED25519_PROGRAM));
      }
      default -> fail(vector.id() + " unknown extra " + vector.extra());
    }
    assertEquals(vector.programIds().size(), instructions.size(), vector.id() + " instruction count");
    return instructions;
  }

  /// A System program transfer encoded here rather than copied from the fixture, so the builder
  /// byte comparison also checks Sava's encoding against `@solana-program/system`'s.
  private static Instruction transfer(final PublicKey from, final PublicKey to) {
    final byte[] data = new byte[Integer.BYTES + Long.BYTES];
    ByteUtil.putInt32LE(data, 0, SYSTEM_TRANSFER_DISCRIMINATOR);
    ByteUtil.putInt64LE(data, Integer.BYTES, TRANSFER_LAMPORTS);
    return Instruction.createInstruction(
        AccountMeta.createInvoked(SYSTEM_PROGRAM),
        List.of(AccountMeta.createWritableSigner(from), AccountMeta.createWrite(to)),
        data
    );
  }

  /// An account-free instruction whose payload is kit's: the property under test is the builder's
  /// framing of the payload, not the memo or precompile encoding.
  private static Instruction accountFree(final Vector vector, final int index, final PublicKey program) {
    assertEquals(program.toBase58(), vector.programIds().get(index), vector.id() + " program " + index);
    return Instruction.createInstruction(AccountMeta.createInvoked(program), List.of(), vector.instructionData().get(index));
  }

  private static List<Signer> signers(final Vector vector) {
    return vector.signerAddresses().stream().map(address -> {
      final var signer = SIGNERS_BY_ADDRESS.get(address);
      assertNotNull(signer, () -> vector.id() + " no seeded signer for " + address);
      return signer;
    }).toList();
  }

  private static List<String> addresses(final AccountMeta[] accounts) {
    return Arrays.stream(accounts).map(account -> account.publicKey().toBase58()).toList();
  }

  private static List<String> addresses(final List<AccountMeta> accounts) {
    return accounts.stream().map(account -> account.publicKey().toBase58()).toList();
  }

  private static Map<String, String> rolesByAddress(final AccountMeta[] accounts) {
    final var roles = new TreeMap<String, String>();
    for (final var account : accounts) {
      final var role = (account.signer() ? "signer" : "non-signer") + '/' + (account.write() ? "writable" : "readonly");
      assertNull(roles.put(account.publicKey().toBase58(), role), "duplicate account " + account.publicKey().toBase58());
    }
    return roles;
  }

  private static byte[] seed(final int value) {
    final byte[] seed = new byte[Signer.KEY_LENGTH];
    Arrays.fill(seed, (byte) value);
    return seed;
  }

  private static Vector vector(final List<Vector> vectors, final String id) {
    return vectors.stream()
        .filter(candidate -> candidate.id().equals(id))
        .findFirst()
        .orElseThrow(() -> new AssertionError("missing fixture vector " + id));
  }

  private static Fixture loadFixture() throws IOException {
    final var input = KitV1VectorTests.class.getResourceAsStream(RESOURCE);
    assertNotNull(input, "missing fixture " + RESOURCE);
    final var metadata = new LinkedHashMap<String, String>();
    final var vectors = new ArrayList<Vector>();
    boolean sawColumns = false;
    try (var reader = new BufferedReader(new InputStreamReader(input, StandardCharsets.UTF_8))) {
      String line;
      int lineNumber = 0;
      while ((line = reader.readLine()) != null) {
        ++lineNumber;
        final int currentLine = lineNumber;
        assertFalse(line.isBlank(), () -> "blank fixture line " + currentLine);
        if (line.startsWith("# ")) {
          assertFalse(sawColumns, () -> "metadata after columns at " + currentLine);
          final int separator = line.indexOf(": ", 2);
          assertTrue(separator > 2, () -> "malformed metadata at " + currentLine);
          final String key = line.substring(2, separator);
          assertNull(metadata.putIfAbsent(key, line.substring(separator + 2)), () -> "duplicate " + key);
        } else if (!sawColumns) {
          assertEquals(COLUMNS, line, () -> "columns at " + currentLine);
          sawColumns = true;
        } else {
          vectors.add(parseVector(line, currentLine));
        }
      }
    }
    assertTrue(sawColumns, "missing columns");
    assertEquals(EXPECTED_METADATA, metadata, "fixture provenance changed");
    assertEquals(EXPECTED_IDS, vectors.stream().map(Vector::id).toList(), "vector inventory");
    return new Fixture(metadata, vectors);
  }

  private static Vector parseVector(final String line, final int lineNumber) {
    final String[] fields = line.split("\\t", -1);
    assertEquals(13, fields.length, () -> "field count at " + lineNumber);
    final String[] header = fields[4].split(":", -1);
    assertEquals(3, header.length, () -> "header at " + lineNumber);
    final var vector = new Vector(
        fields[0],
        fields[1],
        Config.parse(fields[1], lineNumber),
        fields[2],
        Integer.parseInt(fields[3]),
        Integer.parseInt(header[0]),
        Integer.parseInt(header[1]),
        Integer.parseInt(header[2]),
        List.of(fields[5].split(",", -1)),
        List.of(fields[6].split(",", -1)),
        parseByteArrays(fields[7]),
        HEX.parseHex(fields[8]),
        HEX.parseHex(fields[9]),
        parseByteArrays(fields[10]),
        Integer.parseInt(fields[11]),
        Config.parse(fields[12], lineNumber)
    );
    assertEquals(vector.programIds().size(), vector.instructionData().size(), () -> "instruction columns at " + lineNumber);
    assertEquals(vector.numSigners(), vector.signatures().size(), () -> "signature count at " + lineNumber);
    assertTrue(vector.numSigners() <= vector.staticAccounts().size(), () -> "signer count at " + lineNumber);
    return vector;
  }

  private static List<byte[]> parseByteArrays(final String encoded) {
    if (encoded.isEmpty()) {
      return List.of();
    }
    return Arrays.stream(encoded.split(",", -1)).map(HEX::parseHex).toList();
  }

  private static void assertFileSha256(final Map<String, String> metadata,
                                       final String metadataKey,
                                       final String relativePath) throws IOException {
    final var path = generatorPath(relativePath);
    assertEquals(
        metadata.get(metadataKey),
        HEX.formatHex(sha256().digest(Files.readAllBytes(path))),
        () -> "stale fixture provenance for " + path
    );
  }

  private static Path generatorPath(final String relativePath) {
    final var moduleRelative = Path.of(GENERATOR).resolve(relativePath);
    if (Files.isRegularFile(moduleRelative)) {
      return moduleRelative;
    }
    final var repositoryRelative = Path.of("sava-core").resolve(moduleRelative);
    assertTrue(Files.isRegularFile(repositoryRelative), () -> "missing generator input " + relativePath);
    return repositoryRelative;
  }

  private static MessageDigest sha256() {
    try {
      return MessageDigest.getInstance("SHA-256");
    } catch (final NoSuchAlgorithmException e) {
      throw new AssertionError("JDK has no SHA-256 provider", e);
    }
  }

  private record Fixture(Map<String, String> metadata, List<Vector> vectors) {
  }

  private record Built(Transaction transaction, byte[] unsignedMessage, byte[] signedWire) {
  }

  /// The four `V1TransactionConfig` fields as kit was given them (`config`) or read them back
  /// (`read_back_config`): `none` when kit had no config at all, otherwise
  /// `priority_fee:compute_unit_limit:loaded_accounts_data_size_limit:heap_size` with `-` for an
  /// absent field. An absent field and an explicit 0 both read as 0 through Sava's skeleton; only the
  /// mask tells them apart.
  private record Config(boolean present, Long priorityFee, Long computeUnitLimit, Long accountDataSizeLimit, Long heapSize) {

    static Config parse(final String text, final int lineNumber) {
      if (text.equals("none")) {
        return new Config(false, null, null, null, null);
      }
      final String[] fields = text.split(":", -1);
      assertEquals(4, fields.length, () -> "config fields at " + lineNumber);
      return new Config(true, field(fields[0]), field(fields[1]), field(fields[2]), field(fields[3]));
    }

    private static Long field(final String text) {
      return text.equals("-") ? null : Long.valueOf(text);
    }

    long priorityFeeOrZero() {
      return priorityFee == null ? 0L : priorityFee;
    }

    int computeUnitLimitOrZero() {
      return computeUnitLimit == null ? 0 : Math.toIntExact(computeUnitLimit);
    }

    int accountDataSizeLimitOrZero() {
      return accountDataSizeLimit == null ? 0 : Math.toIntExact(accountDataSizeLimit);
    }

    int heapSizeOrZero() {
      return heapSize == null ? 0 : Math.toIntExact(heapSize);
    }

    /// The builder serializes a field only when its value is non-zero, so an explicit 0 is the one
    /// kit input it cannot reproduce.
    boolean hasExplicitZero() {
      final Long zero = 0L;
      return zero.equals(priorityFee) || zero.equals(computeUnitLimit) || zero.equals(accountDataSizeLimit) || zero.equals(heapSize);
    }
  }

  private record Vector(
      String id,
      String configText,
      Config config,
      String extra,
      int configMask,
      int numSigners,
      int numReadonlySigned,
      int numReadonlyUnsigned,
      List<String> staticAccounts,
      List<String> programIds,
      List<byte[]> instructionData,
      byte[] unsignedMessage,
      byte[] signedWire,
      List<byte[]> signatures,
      int readBackVersion,
      Config readBackConfig
  ) {

    boolean builderProducible() {
      return !config.hasExplicitZero();
    }

    List<String> signerAddresses() {
      return staticAccounts.subList(0, numSigners);
    }

    boolean signer(final int accountIndex) {
      return accountIndex < numSigners;
    }

    boolean writable(final int accountIndex) {
      return signer(accountIndex)
          ? accountIndex < numSigners - numReadonlySigned
          : accountIndex < staticAccounts.size() - numReadonlyUnsigned;
    }
  }
}
