package software.sava.core.tx;

import org.junit.jupiter.api.Test;
import software.sava.core.accounts.PublicKey;
import software.sava.core.accounts.Signer;
import software.sava.core.accounts.lookup.AddressLookupTable;
import software.sava.core.accounts.meta.AccountMeta;
import software.sava.core.accounts.meta.LookupTableAccountMeta;
import software.sava.core.encoding.Base58;
import software.sava.core.encoding.ByteUtil;
import software.sava.core.encoding.CompactU16Encoding;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/// First-party defensive conformance for Sava's legacy transaction compiler and signer-slot
/// handling. The committed fixture is generated by pinned Solana SDK Rust APIs; normal Java
/// tests need neither Rust nor network access. Two v0 messages with zero lookups pin the shared
/// transaction framing boundary; address lookup semantics and v1 remain outside this fixture.
final class LegacyMessageConformanceTests {

  private static final String RESOURCE = "/tx/solana-legacy-message-vectors.tsv";
  private static final String COLUMNS =
      "id\tfee_payer_hex\tblockhash_hex\tinstructions\tmessage_hex\t"
          + "signer_seeds_hex\tsignatures_hex\tsignature_prefix_hex\t"
          + "rust_wire_round_trip\tmessage_version";
  private static final HexFormat HEX = HexFormat.of();
  private static final Map<String, String> EXPECTED_METADATA = Map.ofEntries(
      Map.entry("format", "sava-solana-non-lookup-message-v2"),
      Map.entry(
          "property",
          "Sava non-lookup compilation resolves to the same header, account roles, indices, "
              + "instructions, and shortvec boundaries as current Solana Rust messages"
      ),
      Map.entry("solana-sdk", "7e8f4a52f044e7729406bd24ae7c586de92e7f58"),
      Map.entry("solana-message", "4.5.0"),
      Map.entry("kit", "v7.0.0 58df993f4bea388121a872b33038c6af0ca3dd90"),
      Map.entry(
          "kit-oracle",
          "compileTransactionMessage; getOrderedAccountsFromAddressMap; "
              + "getCompiledMessageHeader; getCompiledInstructions; "
              + "getCompiledTransactionMessageEncoder"
      ),
      Map.entry("cargo-lock-sha256", "c83820e7dd41e78b408eef1648d592a0688eb95bd56b9052b8cbbdc17be89088"),
      Map.entry("cargo-manifest-sha256", "6134d3bae365f5841760ef683c6285bfb27af92d7f3da37aea4ba968ab06e8af"),
      Map.entry("generator-source-sha256", "398779740561b0da6d763ae42ada78d0a11dd2585e2a9f4c790d7fda53939211"),
      Map.entry("rust-toolchain", "1.93.0"),
      Map.entry("rust-toolchain-sha256", "92b454c1ccf330de9b94242f73bc3214370fb420d5152baeec12dc82ceef9dcc"),
      Map.entry("vectors", "11")
  );

  @Test
  void legacyCompilationMatchesPinnedSolanaMessageSemanticsAndCanonicalBytes() throws IOException {
    final var fixture = loadFixture();
    for (final var vector : fixture.vectors()) {
      if (vector.versioned()) {
        continue;
      }
      final var instructions = vector.instructions().stream().map(IxSpec::toInstruction).toList();
      if (!vector.rustWireRoundTrip()) {
        // Transaction construction is intentionally permissive. These bytes are useful for
        // analysis even though current Solana transaction decoding rejects the outer framing.
        final var transaction = assertDoesNotThrow(
            () -> Transaction.createTx(vector.feePayer(), instructions),
            vector.id()
        );
        assertEquals((byte) 0x80, transaction.serialized()[0], vector.id());
        assertEquals((byte) 0x80, messageBytes(transaction)[0], vector.id());
        continue;
      }
      final var rustSkeleton = skeletonForMessage(vector.message());

      // Sava has always left tied account keys in HashMap encounter order. Rust uses BTreeMap
      // byte ordering and Kit uses its address comparator, so changing that published order
      // would change otherwise valid transaction IDs. Compare the public builder semantically.
      final var publicBuilder = Transaction.createTx(vector.feePayer(), instructions);
      publicBuilder.setRecentBlockHash(vector.blockhash());
      assertSameLegacyMeaning(rustSkeleton, TransactionSkeleton.deserializeSkeleton(publicBuilder.serialized()), vector.id());

      // The overload accepting already ordered accounts has no tie-break choice. Feeding it the
      // Rust message order gives a direct byte-for-byte serializer/index/shortvec oracle.
      final var canonical = Transaction.createTx(instructions, rustSkeleton.parseAccounts());
      canonical.setRecentBlockHash(vector.blockhash());
      assertArrayEquals(vector.message(), messageBytes(canonical), vector.id());

      if (vector.id().equals("max_account_index_255")) {
        final var versionedWithoutLookups = versionedWithoutLookups(canonical);
        final var versionedSkeleton = TransactionSkeleton.deserializeSkeleton(versionedWithoutLookups);
        assertTrue(versionedSkeleton.isVersioned());
        assertEquals(0, versionedSkeleton.lookupTableAccounts().length);
        assertEquals(
            instructions.getFirst().programId().publicKey(),
            versionedSkeleton.parseProgramAccounts()[0],
            "v0 without lookups must also read program index 255 as raw u8"
        );
      }
    }
  }

  @Test
  void collectionSigningMatchesPinnedSolanaSignerSlotsAndEd25519Bytes() throws IOException {
    for (final var vector : loadFixture().vectors()) {
      if (vector.signerSeeds().isEmpty() || !vector.rustWireRoundTrip()) {
        continue;
      }
      final var rustSkeleton = skeletonForMessage(vector.message());
      final var instructions = vector.instructions().stream().map(IxSpec::toInstruction).toList();
      final var transaction = canonicalTransaction(vector, rustSkeleton);
      transaction.setRecentBlockHash(vector.blockhash());
      final List<Signer> signers = vector.signerSeeds().stream()
          .map(Signer::createFromPrivateKey)
          .toList();

      // A List normally selects the published positional overload. The Collection cast selects
      // the existing by-key contract that mirrors VersionedTransaction::try_new.
      transaction.sign((Collection<Signer>) signers);

      final byte[] serialized = transaction.serialized();
      final int signatureOffset = CompactU16Encoding.getByteLen(serialized, 0);
      assertArrayEquals(
          vector.rustSignaturePrefix(),
          Arrays.copyOf(serialized, signatureOffset),
          vector.id() + " signature count prefix"
      );
      assertEquals(vector.rustSignatures().size(), CompactU16Encoding.decode(serialized, 0), vector.id());
      assertEquals(signatureOffset + (vector.rustSignatures().size() * Transaction.SIGNATURE_LENGTH),
          ((TransactionRecord) transaction).messageOffset(), vector.id());
      for (int index = 0; index < vector.rustSignatures().size(); ++index) {
        assertArrayEquals(
            vector.rustSignatures().get(index),
            Arrays.copyOfRange(
                serialized,
                signatureOffset + (index * Transaction.SIGNATURE_LENGTH),
                signatureOffset + ((index + 1) * Transaction.SIGNATURE_LENGTH)
            ),
            vector.id() + " signature slot " + index
        );
      }
      assertArrayEquals(vector.rustSignatures().getFirst(), transaction.getId(), vector.id());
      assertEquals(Base58.encode(vector.rustSignatures().getFirst()), transaction.getBase58Id(), vector.id());
      assertEquals(transaction.getBase58Id(), TransactionSkeleton.deserializeSkeleton(serialized).id(), vector.id());
    }
  }

  @Test
  void v0WithoutLookupsRecordsTheSignatureBoundaryWithoutBlockingConstruction() throws IOException {
    final var vectors = loadFixture().vectors();
    final var accepted = vectors.stream()
        .filter(candidate -> candidate.id().equals("v0_signature_shortvec_127"))
        .findFirst()
        .orElseThrow();
    final var rejected = vectors.stream()
        .filter(candidate -> candidate.id().equals("v0_signature_shortvec_128"))
        .findFirst()
        .orElseThrow();
    assertTrue(accepted.versioned());
    assertTrue(accepted.rustWireRoundTrip());
    assertArrayEquals(new byte[]{0x7f}, accepted.rustSignaturePrefix());
    assertTrue(rejected.versioned());
    assertFalse(rejected.rustWireRoundTrip());
    assertArrayEquals(new byte[]{(byte) 0x80, 0x01}, rejected.rustSignaturePrefix());

    final var rustSkeleton = skeletonForMessage(accepted.message());
    assertTrue(rustSkeleton.isVersioned());
    assertEquals(0, rustSkeleton.version());
    assertEquals(127, rustSkeleton.numSignatures());
    assertEquals(0, rustSkeleton.lookupTableAccounts().length);

    final var singleTablePath = canonicalVersionedTransaction(accepted, rustSkeleton, false);
    final var multipleTablePath = canonicalVersionedTransaction(accepted, rustSkeleton, true);
    for (final var transaction : List.of(singleTablePath, multipleTablePath)) {
      transaction.setRecentBlockHash(accepted.blockhash());
      assertArrayEquals(accepted.message(), messageBytes(transaction));
      assertArrayEquals(
          accepted.rustSignaturePrefix(),
          Arrays.copyOf(transaction.serialized(), accepted.rustSignaturePrefix().length)
      );
      final var parsed = TransactionSkeleton.deserializeSkeleton(transaction.serialized());
      assertEquals(127, parsed.numSignatures());
      assertEquals(0, parsed.lookupTableAccounts().length);

      final byte[] changedBlockhash = key(0x4a4a).toByteArray();
      Transaction.setBlockHash(transaction.serialized(), changedBlockhash);
      assertArrayEquals(
          changedBlockhash,
          TransactionSkeleton.deserializeSkeleton(transaction.serialized()).blockHash()
      );
    }

    final var rejectedSkeleton = skeletonForMessage(rejected.message());
    for (final var multipleTables : List.of(false, true)) {
      final var transaction = assertDoesNotThrow(
          () -> canonicalVersionedTransaction(rejected, rejectedSkeleton, multipleTables),
          "Sava permits constructing bytes that the RPC will reject"
      );
      transaction.setRecentBlockHash(rejected.blockhash());
      assertEquals((byte) 0x80, transaction.serialized()[0]);
      assertArrayEquals(rejected.message(), messageBytes(transaction));
    }

    final var signer = Signer.createFromPrivateKey(rejected.signerSeeds().getFirst());
    final byte[] output = new byte[
        1 + (128 * Transaction.SIGNATURE_LENGTH) + rejected.message().length
    ];
    final int messageOffset = 1 + (128 * Transaction.SIGNATURE_LENGTH);
    System.arraycopy(rejected.message(), 0, output, messageOffset, rejected.message().length);
    // A buffer assembled by hand declares its own signature count, exactly as every createTx path
    // does at allocation. The helper reads that byte rather than overwriting it, so that a count
    // disagreeing with the caller cannot relocate the message and write a signature over it.
    output[0] = (byte) 128;
    assertDoesNotThrow(
        () -> Transaction.sign(java.util.Collections.nCopies(128, signer), output),
        "the static signing helper retains its permissive byte-oriented contract"
    );
    assertEquals((byte) 0x80, output[0]);
    assertArrayEquals(rejected.message(), Arrays.copyOfRange(output, messageOffset, output.length));  }

  @Test
  void accountAndHeaderUnsignedByteBoundariesRemainPermissiveForAnalysis() throws IOException {
    final var maxIndex = loadFixture().vectors().stream()
        .filter(vector -> vector.id().equals("max_account_index_255"))
        .findFirst()
        .orElseThrow();
    final var maxIndexTx = Transaction.createTx(
        maxIndex.feePayer(),
        maxIndex.instructions().stream().map(IxSpec::toInstruction).toList()
    );
    assertEquals(256, TransactionSkeleton.deserializeSkeleton(maxIndexTx.serialized()).numIncludedAccounts());

    final var tooManyAccounts = Instruction.createInstruction(
        key(0x7fff),
        metas(255, false, false, 0x1000),
        new byte[]{1}
    );
    final var totalOverflow = assertDoesNotThrow(
        () -> Transaction.createTx(key(0x7ffe), tooManyAccounts),
        "RPC-invalid account indices remain constructible"
    );
    assertEquals(257, TransactionSkeleton.deserializeSkeleton(totalOverflow.serialized()).numIncludedAccounts());

    final var readonlyHeaderOverflow = assertDoesNotThrow(
        () -> Transaction.createTx(Instruction.createInstruction(
            key(0x6fff),
            metas(255, false, false, 0x2000),
            new byte[]{2}
        )),
        "header counts continue to narrow to their wire byte"
    );
    final var readonlyOverflowSkeleton = TransactionSkeleton.deserializeSkeleton(readonlyHeaderOverflow.serialized());
    assertEquals(256, readonlyOverflowSkeleton.numIncludedAccounts());
    assertEquals(0, readonlyOverflowSkeleton.numReadonlyUnsignedAccounts());

    final var emptyTable = emptyLookupTable(0x7100);
    final var secondEmptyTable = emptyLookupTable(0x7101);
    final var sortedTooManyAccounts = TransactionRecord.sortV0Accounts(merge(
        AccountMeta.createFeePayer(key(0x70ff)),
        tooManyAccounts
    ));
    final var totalOverflowInstruction = Instruction.createInstruction(
        key(0x7ffd),
        metas(256, false, false, 0x3000),
        new byte[]{3}
    );
    final var totalOverflowAccounts = TransactionRecord.sortV0Accounts(merge(
        AccountMeta.createFeePayer(key(0x70fe)),
        totalOverflowInstruction
    ));
    for (final var multipleTables : List.of(false, true)) {
      final var v0ReadonlyHeaderOverflow = assertDoesNotThrow(
          () -> createVersioned(
              List.of(tooManyAccounts),
              tooManyAccounts.serializedLength(),
              sortedTooManyAccounts,
              emptyTable,
              secondEmptyTable,
              multipleTables
          ),
          "v0 header overflow remains constructible"
      );
      assertEquals(257, TransactionSkeleton.deserializeSkeleton(v0ReadonlyHeaderOverflow.serialized()).numIncludedAccounts());

      final var totalAccountOverflow = assertDoesNotThrow(
          () -> createVersioned(
              List.of(totalOverflowInstruction),
              1 + CompactU16Encoding.getByteLen(256) + 256 + 1 + 1,
              totalOverflowAccounts,
              emptyTable,
              secondEmptyTable,
              multipleTables
          ),
          "v0 account-index overflow remains constructible"
      );
      assertEquals(258, TransactionSkeleton.deserializeSkeleton(totalAccountOverflow.serialized()).numIncludedAccounts());
    }
  }

  @Test
  void fixtureProvenanceMatchesCommittedGeneratorInputs() throws IOException {
    final var metadata = loadFixture().metadata();
    assertFileSha256(metadata, "cargo-lock-sha256", "Cargo.lock");
    assertFileSha256(metadata, "cargo-manifest-sha256", "Cargo.toml");
    assertFileSha256(metadata, "generator-source-sha256", "src/main.rs");
    assertFileSha256(metadata, "rust-toolchain-sha256", "rust-toolchain.toml");
  }

  private static void assertSameLegacyMeaning(
      final TransactionSkeleton expected,
      final TransactionSkeleton actual,
      final String id
  ) {
    assertTrue(actual.isLegacy(), id);
    assertEquals(expected.numSigners(), actual.numSigners(), id + " required signatures");
    assertEquals(expected.numReadonlySignedAccounts(), actual.numReadonlySignedAccounts(), id);
    assertEquals(expected.numReadonlyUnsignedAccounts(), actual.numReadonlyUnsignedAccounts(), id);
    assertEquals(expected.numIncludedAccounts(), actual.numIncludedAccounts(), id);
    assertArrayEquals(expected.blockHash(), actual.blockHash(), id + " blockhash");
    assertEquals(accountRoles(expected.parseAccounts()), accountRoles(actual.parseAccounts()), id);
    assertEquals(expected.serializedInstructionsLength(), actual.serializedInstructionsLength(), id);
    assertArrayEquals(expected.parseProgramAccounts(), actual.parseProgramAccounts(), id);

    final var expectedInstructions = expected.parseLegacyInstructions();
    final var actualInstructions = actual.parseLegacyInstructions();
    assertEquals(expectedInstructions.length, actualInstructions.length, id);
    for (int index = 0; index < expectedInstructions.length; ++index) {
      final var expectedInstruction = expectedInstructions[index];
      final var actualInstruction = actualInstructions[index];
      assertEquals(expectedInstruction.programId().publicKey(), actualInstruction.programId().publicKey(), id);
      assertEquals(expectedInstruction.accounts(), actualInstruction.accounts(), id + " accounts " + index);
      assertArrayEquals(expectedInstruction.copyData(), actualInstruction.copyData(), id + " data " + index);

      final var expectedWithoutAccounts = expected.parseInstructionsWithoutAccounts()[index];
      final var actualWithoutAccounts = actual.parseInstructionsWithoutAccounts()[index];
      assertEquals(expectedWithoutAccounts.programId(), actualWithoutAccounts.programId(), id);
      assertArrayEquals(expectedWithoutAccounts.copyData(), actualWithoutAccounts.copyData(), id);

      final var discriminator = expectedInstruction.wrapDiscriminator(1);
      final var filtered = actual.filterInstructions(actual.parseAccounts(), discriminator);
      final var filteredWithoutAccounts = actual.filterInstructionsWithoutAccounts(discriminator);
      assertEquals(expectedInstruction.programId(), filtered[0].programId(), id);
      assertEquals(expectedInstruction.programId().publicKey(), filteredWithoutAccounts[0].programId().publicKey(), id);
    }
  }

  private static Map<PublicKey, Role> accountRoles(final AccountMeta[] accounts) {
    final var roles = new HashMap<PublicKey, Role>(accounts.length);
    for (final var account : accounts) {
      assertNull(roles.put(
          account.publicKey(),
          new Role(account.feePayer(), account.signer(), account.write())
      ), () -> "duplicate compiled account " + account.publicKey());
    }
    return roles;
  }

  private static TransactionSkeleton skeletonForMessage(final byte[] message) {
    final int numSignatures = (message[0] & 0x80) == 0
        ? Byte.toUnsignedInt(message[0])
        : Byte.toUnsignedInt(message[1]);
    final byte[] transaction = new byte[
        CompactU16Encoding.getByteLen(numSignatures)
            + (numSignatures * Transaction.SIGNATURE_LENGTH)
            + message.length
        ];
    int offset = CompactU16Encoding.encodeLength(transaction, 0, numSignatures);
    offset += numSignatures * Transaction.SIGNATURE_LENGTH;
    System.arraycopy(message, 0, transaction, offset, message.length);
    return TransactionSkeleton.deserializeSkeleton(transaction);
  }

  private static Transaction canonicalTransaction(
      final Vector vector,
      final TransactionSkeleton rustSkeleton
  ) {
    if (vector.versioned()) {
      return canonicalVersionedTransaction(vector, rustSkeleton, false);
    }
    return Transaction.createTx(
        vector.instructions().stream().map(IxSpec::toInstruction).toList(),
        rustSkeleton.parseAccounts()
    );
  }

  private static Transaction canonicalVersionedTransaction(
      final Vector vector,
      final TransactionSkeleton rustSkeleton,
      final boolean multipleTables
  ) {
    final var instructions = vector.instructions().stream().map(IxSpec::toInstruction).toList();
    final int serializedLength = instructions.stream().mapToInt(Instruction::serializedLength).sum();
    return createVersioned(
        instructions,
        serializedLength,
        rustSkeleton.parseAccounts(),
        emptyLookupTable(0x7200),
        emptyLookupTable(0x7201),
        multipleTables
    );
  }

  private static Transaction createVersioned(
      final List<Instruction> instructions,
      final int serializedLength,
      final AccountMeta[] sortedAccounts,
      final AddressLookupTable firstTable,
      final AddressLookupTable secondTable,
      final boolean multipleTables
  ) {
    return multipleTables
        ? Transaction.createTx(
            instructions,
            serializedLength,
            sortedAccounts.clone(),
            new LookupTableAccountMeta[]{
                LookupTableAccountMeta.createMeta(firstTable),
                LookupTableAccountMeta.createMeta(secondTable)
            }
        )
        : Transaction.createTx(
            instructions,
            serializedLength,
            sortedAccounts.clone(),
            firstTable
        );
  }

  private static AddressLookupTable emptyLookupTable(final int address) {
    final byte[] data = new byte[AddressLookupTable.LOOKUP_TABLE_META_SIZE];
    ByteUtil.putInt32LE(data, AddressLookupTable.DISCRIMINATOR_OFFSET, 1);
    ByteUtil.putInt64LE(data, AddressLookupTable.DEACTIVATION_SLOT_OFFSET, -1L);
    return AddressLookupTable.read(key(address), data);
  }

  private static Map<PublicKey, AccountMeta> merge(
      final AccountMeta feePayer,
      final Instruction instruction
  ) {
    final var accounts = new HashMap<PublicKey, AccountMeta>();
    TransactionRecord.mergeAccounts(feePayer, accounts, List.of(instruction));
    return accounts;
  }

  private static byte[] messageBytes(final Transaction transaction) {
    final var record = (TransactionRecord) transaction;
    return Arrays.copyOfRange(record.serialized(), record.messageOffset(), record.serialized().length);
  }

  private static byte[] versionedWithoutLookups(final Transaction transaction) {
    final var record = (TransactionRecord) transaction;
    final byte[] legacy = record.serialized();
    final byte[] versioned = new byte[legacy.length + 2];
    System.arraycopy(legacy, 0, versioned, 0, record.messageOffset());
    versioned[record.messageOffset()] = (byte) 0x80;
    System.arraycopy(
        legacy,
        record.messageOffset(),
        versioned,
        record.messageOffset() + 1,
        legacy.length - record.messageOffset()
    );
    // One extra byte beyond the version prefix is the compact-u16 zero lookup-table count.
    versioned[versioned.length - 1] = 0;
    return versioned;
  }

  private static List<AccountMeta> metas(
      final int count,
      final boolean signer,
      final boolean writable,
      final int keyBase
  ) {
    final var metas = new ArrayList<AccountMeta>(count);
    for (int index = 0; index < count; ++index) {
      metas.add(AccountMeta.createMeta(key(keyBase + index), writable, signer));
    }
    return metas;
  }

  private static PublicKey key(final int value) {
    final byte[] bytes = new byte[PublicKey.PUBLIC_KEY_LENGTH];
    bytes[0] = (byte) (value >>> 8);
    bytes[1] = (byte) value;
    bytes[31] = 0x5a;
    return PublicKey.createPubKey(bytes);
  }

  private static Fixture loadFixture() throws IOException {
    final var input = LegacyMessageConformanceTests.class.getResourceAsStream(RESOURCE);
    assertNotNull(input, "missing fixture " + RESOURCE);
    final var metadata = new LinkedHashMap<String, String>();
    final var vectors = new ArrayList<Vector>();
    boolean sawColumns = false;
    try (var reader = new BufferedReader(new InputStreamReader(input, StandardCharsets.UTF_8))) {
      String line;
      int lineNumber = 0;
      while ((line = reader.readLine()) != null) {
        ++lineNumber;
        final int currentLine = lineNumber;
        assertFalse(line.isBlank(), () -> "blank fixture line " + currentLine);
        if (line.startsWith("# ")) {
          assertFalse(sawColumns, () -> "metadata after columns at " + currentLine);
          final int separator = line.indexOf(": ", 2);
          assertTrue(separator > 2, () -> "malformed metadata at " + currentLine);
          final String key = line.substring(2, separator);
          assertNull(metadata.putIfAbsent(key, line.substring(separator + 2)), () -> "duplicate " + key);
        } else if (!sawColumns) {
          assertEquals(COLUMNS, line, () -> "columns at " + currentLine);
          sawColumns = true;
        } else {
          vectors.add(parseVector(line, currentLine));
        }
      }
    }
    assertTrue(sawColumns, "missing columns");
    assertEquals(EXPECTED_METADATA, metadata, "fixture provenance changed");
    assertEquals(11, vectors.size());
    return new Fixture(metadata, vectors);
  }

  private static Vector parseVector(final String line, final int lineNumber) {
    final String[] fields = line.split("\\t", -1);
    assertEquals(10, fields.length, () -> "field count at " + lineNumber);
    return new Vector(
        fields[0],
        PublicKey.createPubKey(HEX.parseHex(fields[1])),
        HEX.parseHex(fields[2]),
        parseInstructions(fields[3]),
        HEX.parseHex(fields[4]),
        parseByteArrays(fields[5]),
        parseByteArrays(fields[6]),
        HEX.parseHex(fields[7]),
        parseBoolean(fields[8], lineNumber),
        parseMessageVersion(fields[9], lineNumber)
    );
  }

  private static boolean parseMessageVersion(final String value, final int lineNumber) {
    assertTrue(value.equals("legacy") || value.equals("v0"), () -> "message version at " + lineNumber);
    return value.equals("v0");
  }

  private static List<IxSpec> parseInstructions(final String encoded) {
    final var instructions = new ArrayList<IxSpec>();
    for (final var encodedInstruction : encoded.split(";", -1)) {
      final String[] fields = encodedInstruction.split("\\|", -1);
      assertEquals(3, fields.length, () -> "instruction fields in " + encodedInstruction);
      final var accounts = new ArrayList<MetaSpec>();
      if (!fields[1].isEmpty()) {
        for (final var encodedMeta : fields[1].split(",", -1)) {
          final String[] meta = encodedMeta.split(":", -1);
          assertEquals(3, meta.length, () -> "meta fields in " + encodedMeta);
          accounts.add(new MetaSpec(
              PublicKey.createPubKey(HEX.parseHex(meta[0])),
              meta[1].equals("1"),
              meta[2].equals("1")
          ));
        }
      }
      instructions.add(new IxSpec(
          PublicKey.createPubKey(HEX.parseHex(fields[0])),
          accounts,
          HEX.parseHex(fields[2])
      ));
    }
    return instructions;
  }

  private static List<byte[]> parseByteArrays(final String encoded) {
    if (encoded.isEmpty()) {
      return List.of();
    }
    return Arrays.stream(encoded.split(",", -1)).map(HEX::parseHex).toList();
  }

  private static boolean parseBoolean(final String value, final int lineNumber) {
    assertTrue(value.equals("true") || value.equals("false"), () -> "boolean at " + lineNumber);
    return Boolean.parseBoolean(value);
  }

  private static void assertFileSha256(
      final Map<String, String> metadata,
      final String metadataKey,
      final String relativePath
  ) throws IOException {
    final var path = generatorPath(relativePath);
    assertEquals(
        metadata.get(metadataKey),
        HEX.formatHex(sha256().digest(Files.readAllBytes(path))),
        () -> "stale fixture provenance for " + path
    );
  }

  private static Path generatorPath(final String relativePath) {
    final var moduleRelative = Path.of("src/test/solana/legacy-message-vectors").resolve(relativePath);
    if (Files.isRegularFile(moduleRelative)) {
      return moduleRelative;
    }
    final var repositoryRelative = Path.of("sava-core").resolve(moduleRelative);
    assertTrue(Files.isRegularFile(repositoryRelative), () -> "missing generator input " + relativePath);
    return repositoryRelative;
  }

  private static MessageDigest sha256() {
    try {
      return MessageDigest.getInstance("SHA-256");
    } catch (final NoSuchAlgorithmException e) {
      throw new AssertionError("JDK has no SHA-256 provider", e);
    }
  }

  private record Fixture(Map<String, String> metadata, List<Vector> vectors) {
  }

  private record Vector(
      String id,
      PublicKey feePayer,
      byte[] blockhash,
      List<IxSpec> instructions,
      byte[] message,
      List<byte[]> signerSeeds,
      List<byte[]> rustSignatures,
      byte[] rustSignaturePrefix,
      boolean rustWireRoundTrip,
      boolean versioned
  ) {
  }

  private record IxSpec(PublicKey program, List<MetaSpec> accounts, byte[] data) {

    Instruction toInstruction() {
      return Instruction.createInstruction(
          program,
          accounts.stream().map(MetaSpec::toAccountMeta).toList(),
          data
      );
    }
  }

  private record MetaSpec(PublicKey key, boolean signer, boolean writable) {

    AccountMeta toAccountMeta() {
      return AccountMeta.createMeta(key, writable, signer);
    }
  }

  private record Role(boolean feePayer, boolean signer, boolean writable) {
  }
}
