package software.sava.core.tx;

import org.junit.jupiter.api.Test;
import software.sava.core.accounts.PublicKey;
import software.sava.core.accounts.Signer;
import software.sava.core.encoding.Base58;
import software.sava.core.encoding.ByteUtil;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

import static org.junit.jupiter.api.Assertions.*;

/// First-party defensive conformance for Sava's SIMD-0385 transaction v1 reader. The committed
/// fixture is generated by a locked Rust crate driving `solana-message` 4.5.0's `v1` module and
/// `solana-transaction` 4.2.0's `VersionedTransaction`, at the same pinned `solana-sdk` commit the
/// sibling legacy fixture uses; normal Java tests need neither Rust nor network access.
///
/// Every offset, length, mask value, header, signature, and error in the fixture is produced by
/// executing Rust rather than by Sava, so this is the external oracle for the v1 wire format:
/// a self-consistent off-by-one in a Sava constant fails here instead of hiding behind Sava's own
/// round trip. Address lookup semantics, the legacy and v0 message formats, and runtime
/// compute-budget behaviour are outside this fixture.
///
/// Where Sava is deliberately more permissive than Rust's `v1::Message::validate` — it is a
/// byte-oriented builder and analyzer that leaves submission validation to the RPC — the current
/// behaviour is pinned rather than forced to reject, and the divergence is called out at the
/// assertion. See [#v1PopulationLimitsAreReportedRatherThanRejected] and
/// [#v1OutOfRangeInstructionAccountIndexIsRejected].
///
/// That permissiveness stops where a message would parse into a plausible-looking WRONG view rather
/// than an invalid-but-faithful one — see [#v1UnknownConfigMaskBitsAreRejectedAsRustRejectsThem],
/// which is the same line the two header rules draw.
final class V1MessageConformanceTests {

  private static final String RESOURCE = "/tx/solana-v1-message-vectors.tsv";
  private static final String GENERATOR = "src/test/solana/v1-message-vectors";
  private static final String COLUMNS =
      "id\tcategory\theader\tconfig_mask\tnum_addresses\tnum_instructions\tmessage_len\t"
          + "offsets\tconfig_values\tmessage_hex\taddresses_hex\tinstructions\t"
          + "signer_seeds_hex\tsignatures_hex\tsignature_block_offset\ttransaction_hex\t"
          + "rust_validate\trust_validate_error\trust_deserialize\trust_deserialize_error\t"
          + "rust_deserialize_with_prefix\trust_wire_round_trip";
  private static final int VECTOR_COUNT = 47;
  private static final HexFormat HEX = HexFormat.of();

  private static final String PRIORITY_FEE = "priority_fee";
  private static final String COMPUTE_UNIT_LIMIT = "compute_unit_limit";
  private static final String ACCOUNT_DATA_SIZE_LIMIT = "loaded_accounts_data_size_limit";
  private static final String HEAP_SIZE = "heap_size";

  private static final Map<String, String> EXPECTED_METADATA = Map.ofEntries(
      Map.entry("format", "sava-solana-v1-message-v1"),
      Map.entry(
          "property",
          "Sava transaction v1 framing, field offsets, config mask arithmetic, header derivation, "
              + "and validation limits match SIMD-0385 as implemented by current Solana Rust"
      ),
      Map.entry("simd", "0385-transaction-v1"),
      Map.entry("solana-sdk", "7e8f4a52f044e7729406bd24ae7c586de92e7f58"),
      Map.entry("solana-message", "4.5.0"),
      Map.entry("solana-transaction", "4.2.0"),
      Map.entry("wincode", "0.6.1"),
      Map.entry(
          "v1-constants",
          "V1_PREFIX=129 FIXED_HEADER_SIZE=41 MAX_ADDRESSES=64 MAX_INSTRUCTIONS=64 "
              + "MAX_SIGNATURES=12 MIN_HEAP_SIZE=32768 MAX_HEAP_SIZE=262144 MAX_TRANSACTION_SIZE=4096"
      ),
      Map.entry(
          "config-mask-bits",
          "PRIORITY_FEE=3 u64 COMPUTE_UNIT_LIMIT=4 u32 LOADED_ACCOUNTS_DATA_SIZE=8 u32 "
              + "HEAP_SIZE=16 u32 KNOWN_BITS=31"
      ),
      Map.entry(
          "framing",
          "message-first; signatures trail with no compact-u16 count; "
              + "signature_block_offset equals the serialized message length"
      ),
      Map.entry(
          "signed-payload",
          "VersionedMessage::serialize() including the 0x81 prefix is the ed25519 signed payload"
      ),
      Map.entry("v1-message-serialize-emits-version-prefix", "true"),
      Map.entry("v1-message-deserialize-consumes-version-prefix", "false"),
      Map.entry("v1-message-deserialize-with-prefix-error", "InvalidValue"),
      Map.entry("cargo-lock-sha256", "509d17e74329aae6ee082508b3ddd46205032a4ef49394c9623e03e5f0940bc9"),
      Map.entry("cargo-manifest-sha256", "3a122bd97eab42c5f5fb3c984f9e23d664f366fd3eb0e9a75edba6b25cf18549"),
      Map.entry("generator-source-sha256", "4a7b20a6b1756b41e5e814372d2015f65cb601b565c721d31cf6efd5af473025"),
      Map.entry("rust-toolchain", "1.93.0"),
      Map.entry("rust-toolchain-sha256", "92b454c1ccf330de9b94242f73bc3214370fb420d5152baeec12dc82ceef9dcc"),
      Map.entry("vectors", Integer.toString(VECTOR_COUNT))
  );

  @Test
  void fixtureProvenanceMatchesCommittedGeneratorInputs() throws IOException {
    final var metadata = loadFixture().metadata();
    assertFileSha256(metadata, "cargo-lock-sha256", "Cargo.lock");
    assertFileSha256(metadata, "cargo-manifest-sha256", "Cargo.toml");
    assertFileSha256(metadata, "generator-source-sha256", "src/main.rs");
    assertFileSha256(metadata, "rust-toolchain-sha256", "rust-toolchain.toml");
  }

  /// v1 inverts the legacy framing: the serialized message leads, the signature block trails, and
  /// there is no compact-u16 signature count anywhere on the wire. The signature count comes from
  /// the message header, so the boundary between message and signatures is only implied — which is
  /// exactly what Sava has to rediscover from the bytes.
  @Test
  void v1FramingTrailsSignaturesAfterTheSignedMessage() throws IOException {
    int framingVectors = 0;
    for (final var vector : loadFixture().vectors()) {
      if (!vector.category().equals("framing")) {
        continue;
      }
      ++framingVectors;
      final byte[] wire = vector.wire();
      // The Rust VersionedTransaction wire bytes are the message followed by the raw signatures.
      assertArrayEquals(vector.transaction(), wire, vector.id() + " transaction wire");
      assertEquals(TxBuilderImpl.V1_VERSION_BYTE, wire[0], vector.id() + " leads with the version byte, not a count");
      assertEquals(vector.numRequiredSignatures(), vector.signatures().size(), vector.id());
      assertEquals(
          vector.messageLen() + (vector.signatures().size() * Transaction.SIGNATURE_LENGTH),
          wire.length,
          vector.id() + " has no compact-u16 signature count"
      );
      assertEquals(vector.messageLen(), vector.signatureBlockOffset(), vector.id());

      final var skeleton = TransactionSkeleton.deserializeSkeleton(wire);
      assertInstanceOf(V1TransactionSkeleton.class, skeleton, vector.id() + " dispatches to the v1 skeleton");
      assertTrue(skeleton.isVersioned(), vector.id());
      assertFalse(skeleton.isLegacy(), vector.id());
      assertEquals(1, skeleton.version(), vector.id());
      assertEquals(0, skeleton.lookupTableAccounts().length, vector.id());
      assertEquals(vector.numRequiredSignatures(), skeleton.numSignatures(), vector.id());

      // Sava recovers Rust's signature-block offset from the message itself, not from the length.
      assertEquals(
          vector.signatureBlockOffset(),
          V1TransactionSkeleton.requireSignatureBlockOffset(wire),
          vector.id() + " signature block offset"
      );
      assertEquals(vector.messageLen(), V1TransactionSkeleton.messageEnd(wire), vector.id() + " message end");
      assertArrayEquals(
          vector.message(),
          Arrays.copyOf(wire, vector.signatureBlockOffset()),
          vector.id() + " message bytes preceding the signature block"
      );
      for (int index = 0; index < vector.signatures().size(); ++index) {
        assertArrayEquals(
            vector.signatures().get(index),
            Arrays.copyOfRange(
                wire,
                vector.signatureBlockOffset() + (index * Transaction.SIGNATURE_LENGTH),
                vector.signatureBlockOffset() + ((index + 1) * Transaction.SIGNATURE_LENGTH)
            ),
            vector.id() + " signature slot " + index
        );
      }
      assertEquals(Base58.encode(vector.signatures().getFirst()), skeleton.id(), vector.id() + " transaction id");
      assertArrayEquals(vector.signatures().getFirst(), Transaction.getId(wire), vector.id());

      assertInstructionsMatchRust(vector, skeleton);

      // The signed payload is VersionedMessage::serialize(), which includes the 0x81 prefix. Sign
      // the zeroed wire and require Rust's exact ed25519 bytes back in Rust's exact slots. The
      // seeds are recorded in reverse slot order, so the by-key Collection overload has to place
      // them; a List would select the positional overload instead.
      final byte[] unsigned = wire.clone();
      Arrays.fill(unsigned, vector.signatureBlockOffset(), unsigned.length, (byte) 0);
      final var transaction = TransactionSkeleton.deserializeSkeleton(unsigned).createTransaction();
      final List<Signer> signers = vector.signerSeeds().stream().map(Signer::createFromPrivateKey).toList();
      transaction.sign((Collection<Signer>) signers);
      assertArrayEquals(wire, transaction.serialized(), vector.id() + " signed transaction bytes");
      assertEquals(Base58.encode(vector.signatures().getFirst()), transaction.getBase58Id(), vector.id());
    }
    assertEquals(3, framingVectors, "framing vectors");
  }

  /// The external pin for `V1_CONFIG_MASK_OFFSET`, `V1_RECENT_BLOCK_HASH_INDEX`,
  /// `V1_ACCOUNTS_OFFSET`, and the derived instruction-block offsets. Rust recomputes every offset
  /// in the fixture from its own emitted bytes, so these are absolute wire positions rather than
  /// anything Sava restates.
  @Test
  void v1FieldOffsetsMatchPinnedRustAbsoluteOffsets() throws IOException {
    int checked = 0;
    for (final var vector : loadFixture().vectors()) {
      if (!savaAgreesOnLayout(vector)) {
        continue;
      }
      ++checked;
      final byte[] wire = vector.wire();
      final var id = vector.id();
      final var offsets = vector.offsets();

      // Fixed prefix: version byte, three header counts, u32 mask, 32 byte lifetime specifier,
      // NumInstructions, NumAddresses, then the addresses.
      assertEquals(0, offsets.get("version").intValue(), id);
      assertEquals(TxBuilderImpl.V1_VERSION_BYTE, wire[offsets.get("version")], id);
      assertEquals(1, offsets.get("header").intValue(), id);
      assertEquals(V1TransactionSkeleton.V1_CONFIG_MASK_OFFSET, offsets.get("config_mask").intValue(), id + " config mask offset");
      assertEquals(V1TransactionSkeleton.V1_RECENT_BLOCK_HASH_INDEX, offsets.get("lifetime_specifier").intValue(), id + " blockhash offset");
      assertEquals(V1TransactionSkeleton.V1_ACCOUNTS_OFFSET - 2, offsets.get("num_instructions").intValue(), id);
      assertEquals(V1TransactionSkeleton.V1_ACCOUNTS_OFFSET - 1, offsets.get("num_addresses").intValue(), id);
      assertEquals(V1TransactionSkeleton.V1_ACCOUNTS_OFFSET, offsets.get("addresses").intValue(), id + " accounts offset");
      assertEquals(vector.numInstructions(), wire[offsets.get("num_instructions")] & 0xFF, id);
      assertEquals(vector.numAddresses(), wire[offsets.get("num_addresses")] & 0xFF, id);

      final var skeleton = TransactionSkeleton.deserializeSkeleton(wire);
      assertEquals(V1TransactionSkeleton.V1_RECENT_BLOCK_HASH_INDEX, skeleton.recentBlockHashIndex(), id);
      assertArrayEquals(
          Arrays.copyOfRange(wire, offsets.get("lifetime_specifier"), offsets.get("lifetime_specifier") + Transaction.BLOCK_HASH_LENGTH),
          skeleton.blockHash(),
          id + " blockhash"
      );
      assertEquals(vector.numRequiredSignatures(), skeleton.numSignatures(), id);
      assertEquals(vector.numReadonlySigned(), skeleton.numReadonlySignedAccounts(), id);
      assertEquals(vector.numReadonlyUnsigned(), skeleton.numReadonlyUnsignedAccounts(), id);
      assertEquals(vector.numAddresses(), skeleton.numIncludedAccounts(), id);
      assertEquals(vector.numAddresses(), skeleton.numAccounts(), id);
      assertEquals(0, skeleton.numIndexedAccounts(), id + " v1 loads no lookup table accounts");
      assertEquals(vector.numInstructions(), skeleton.numInstructions(), id);
      assertArrayEquals(
          Arrays.copyOfRange(wire, offsets.get("addresses"), offsets.get("addresses") + PublicKey.PUBLIC_KEY_LENGTH),
          skeleton.feePayer().toByteArray(),
          id + " fee payer is the first address"
      );

      // Addresses precede the config values, which precede all instruction headers, which precede
      // all instruction payloads.
      assertEquals(
          offsets.get("addresses") + (vector.numAddresses() * PublicKey.PUBLIC_KEY_LENGTH),
          offsets.get("config_values").intValue(),
          id + " config values follow the addresses"
      );
      assertEquals(skeleton.instructionsOffset(), offsets.get("instruction_headers").intValue(), id + " instruction headers offset");
      assertEquals(
          skeleton.instructionsOffset() + (vector.numInstructions() * TxBuilderImpl.V1_INSTRUCTION_HEADER_LENGTH),
          offsets.get("instruction_payloads").intValue(),
          id + " instruction payloads follow the fixed width headers"
      );
      assertEquals(
          offsets.get("message_end").intValue(),
          skeleton.instructionsOffset() + skeleton.serializedInstructionsLength(),
          id + " serialized instructions length"
      );
      assertEquals(vector.messageLen(), offsets.get("message_end").intValue(), id);
      assertEquals(vector.messageLen(), V1TransactionSkeleton.messageEnd(wire), id + " message end");
      assertEquals(vector.signatureBlockOffset(), V1TransactionSkeleton.requireSignatureBlockOffset(wire), id);

      // Every instruction header is (u8 programIdIndex, u8 numAccounts, u16 LE numDataBytes), and
      // the payload walk has to land exactly on Rust's message end.
      int payload = offsets.get("instruction_payloads");
      for (int i = 0, header = skeleton.instructionsOffset(); i < vector.numInstructions(); ++i, header += TxBuilderImpl.V1_INSTRUCTION_HEADER_LENGTH) {
        payload += (wire[header + 1] & 0xFF) + (ByteUtil.getInt16LE(wire, header + 2) & 0xFFFF);
      }
      assertEquals(offsets.get("message_end").intValue(), payload, id + " instruction payload walk");
    }
    assertEquals(41, checked, "vectors with a layout Rust and Sava both accept");
  }

  /// All sixteen valid `TransactionConfigMask` combinations, against the values and absolute
  /// offsets Rust recorded. The priority fee is a `u64` behind a two-bit mask pair, so a reader
  /// which allots it a single four-byte slot misplaces every config value after it — the mixed
  /// masks below are what catch that.
  @Test
  void v1ConfigValuesMatchPinnedRustMaskArithmetic() throws IOException {
    final var masksSeen = new TreeSet<Long>();
    for (final var vector : loadFixture().vectors()) {
      if (!savaAgreesOnLayout(vector)) {
        continue;
      }
      final byte[] wire = vector.wire();
      final var id = vector.id();
      final var skeleton = (V1TransactionSkeleton) TransactionSkeleton.deserializeSkeleton(wire);
      if (vector.category().equals("config_mask")) {
        masksSeen.add(vector.configMask());
      }

      assertEquals(vector.configMask(), Integer.toUnsignedLong(skeleton.configMask()), id + " config mask");
      assertEquals(
          vector.configMask(),
          Integer.toUnsignedLong(ByteUtil.getInt32LE(wire, V1TransactionSkeleton.V1_CONFIG_MASK_OFFSET)),
          id + " mask is a u32 LE at offset 4"
      );

      assertConfigValue(vector, wire, PRIORITY_FEE, V1TransactionSkeleton.PRIORITY_FEE_MASK, skeleton.priorityFeeLamports());
      assertConfigValue(vector, wire, COMPUTE_UNIT_LIMIT, V1TransactionSkeleton.COMPUTE_UNIT_LIMIT_MASK,
          Integer.toUnsignedLong(skeleton.computeUnitLimit()));
      assertConfigValue(vector, wire, ACCOUNT_DATA_SIZE_LIMIT, V1TransactionSkeleton.ACCOUNT_DATA_SIZE_LIMIT_MASK,
          Integer.toUnsignedLong(skeleton.accountDataSizeLimit()));
      assertConfigValue(vector, wire, HEAP_SIZE, V1TransactionSkeleton.HEAP_SIZE_MASK,
          Integer.toUnsignedLong(skeleton.heapSize()));

      // The config block starts where the addresses end, and is four bytes per set mask bit —
      // which only works out because the priority fee occupies two bits and eight bytes.
      final int blockStart = vector.offsets().get("config_values");
      assertEquals(
          blockStart + (Long.bitCount(vector.configMask()) << 2),
          vector.offsets().get("instruction_headers").intValue(),
          id + " config block width"
      );
      final var priorityFee = vector.configValues().get(PRIORITY_FEE);
      if (priorityFee != null) {
        assertEquals(blockStart, priorityFee.offset(), id + " the priority fee sorts first");
        for (final var name : List.of(COMPUTE_UNIT_LIMIT, ACCOUNT_DATA_SIZE_LIMIT, HEAP_SIZE)) {
          final var next = vector.configValues().get(name);
          if (next != null) {
            assertTrue(
                next.offset() >= priorityFee.offset() + Long.BYTES,
                id + " " + name + " must clear the eight byte priority fee"
            );
          }
        }
      }
    }
    assertEquals(
        Set.of(0L, 3L, 4L, 7L, 8L, 11L, 12L, 15L, 16L, 19L, 20L, 23L, 24L, 27L, 28L, 31L),
        masksSeen,
        "all sixteen valid config mask combinations"
    );
  }

  /// Rust compiles the address array — ordering, signer/writable promotion across instructions, and
  /// duplicate references collapsing to one address. Sava derives the roles back out of the header
  /// partition, so this checks Sava's read against Rust's write.
  @Test
  void v1AccountOrderAndRolesMatchPinnedRustCompilation() throws IOException {
    int orderingVectors = 0;
    for (final var vector : loadFixture().vectors()) {
      if (!vector.category().equals("ordering")) {
        continue;
      }
      ++orderingVectors;
      final var id = vector.id();
      final var skeleton = TransactionSkeleton.deserializeSkeleton(vector.wire());
      final var accounts = skeleton.parseAccounts();

      assertEquals(vector.numAddresses(), accounts.length, id + " address count");
      assertEquals(vector.addresses().size(), accounts.length, id);
      for (int index = 0; index < accounts.length; ++index) {
        assertArrayEquals(
            vector.addresses().get(index),
            accounts[index].publicKey().toByteArray(),
            id + " address " + index + " ordering"
        );
        // Rust's header partitions the array: signers first, writable before readonly in each half.
        final boolean signer = index < vector.numRequiredSignatures();
        final boolean writable = signer
            ? index < vector.numRequiredSignatures() - vector.numReadonlySigned()
            : index < vector.numAddresses() - vector.numReadonlyUnsigned();
        assertEquals(signer, accounts[index].signer(), id + " address " + index + " signer");
        assertEquals(writable, accounts[index].write(), id + " address " + index + " writable");
        assertEquals(index == 0, accounts[index].feePayer(), id + " address " + index + " fee payer");
      }

      // The roles Rust compiled are the union of every reference, with the fee payer always a
      // writable signer. Promotion, duplicate collapsing, and program accounts all fall out of it.
      final var expected = new HashMap<String, Role>(accounts.length);
      for (final var address : vector.addresses()) {
        expected.put(HEX.formatHex(address), new Role(false, false));
      }
      expected.put(HEX.formatHex(vector.addresses().getFirst()), new Role(true, true));
      for (final var instruction : vector.instructions()) {
        for (final var meta : instruction.accounts()) {
          final var key = HEX.formatHex(meta.key());
          final var current = expected.get(key);
          assertNotNull(current, id + " instruction references an uncompiled address " + key);
          expected.put(key, new Role(current.signer() || meta.signer(), current.writable() || meta.writable()));
        }
      }
      for (final var account : accounts) {
        final var key = HEX.formatHex(account.publicKey().toByteArray());
        assertEquals(
            expected.get(key),
            new Role(account.signer(), account.write()),
            id + " compiled role for " + key
        );
      }

      assertInstructionsMatchRust(vector, skeleton);
    }
    assertEquals(3, orderingVectors, "ordering vectors");
  }

  /// The two header rules Sava does enforce, because both partition the address array: violating
  /// either does not produce an invalid-but-faithful view, it produces a plausible-looking wrong
  /// one. Rust reports them from `validate()` as `ZeroSigners` and
  /// `NotEnoughAddressesForSignatures`.
  @Test
  void v1HeaderRulesThatPartitionTheAddressArrayAreRejected() throws IOException {
    final var vectors = loadFixture().vectors();

    final var zeroSigners = vector(vectors, "reject_readonly_signed_equals_required");
    assertFalse(zeroSigners.rustValidate());
    assertEquals("ZeroSigners", zeroSigners.rustValidateError());
    final var zeroSignersFailure = assertThrows(
        IllegalStateException.class,
        () -> TransactionSkeleton.deserializeSkeleton(zeroSigners.wire()),
        zeroSigners.id()
    );
    assertEquals(
        "A v1 transaction requiring 2 signatures may not load 2 of them as read-only; the fee payer must be writable.",
        zeroSignersFailure.getMessage()
    );

    final var notEnoughAddresses = vector(vectors, "reject_not_enough_addresses_for_signatures");
    assertFalse(notEnoughAddresses.rustValidate());
    assertEquals("NotEnoughAddressesForSignatures", notEnoughAddresses.rustValidateError());
    final var notEnoughAddressesFailure = assertThrows(
        IllegalStateException.class,
        () -> TransactionSkeleton.deserializeSkeleton(notEnoughAddresses.wire()),
        notEnoughAddresses.id()
    );
    assertEquals(
        "A v1 transaction with 4 addresses cannot hold 3 signers and 2 read-only non-signers.",
        notEnoughAddressesFailure.getMessage()
    );
  }

  /// A half-set priority fee mask pair is malformed on the wire — `TransactionConfigMask` requires
  /// both bits — and it changes the width of the config block, so Sava rejects it exactly as Rust's
  /// reader does. These bytes can only be produced by patching a serialized message, which is why
  /// Rust reports them from `deserialize` (`InvalidValue`) rather than from `validate`.
  @Test
  void v1HalfSetPriorityFeeMaskPairIsRejected() throws IOException {
    int checked = 0;
    for (final var vector : loadFixture().vectors()) {
      if (!vector.id().startsWith("reject_config_mask_priority_fee_")) {
        continue;
      }
      ++checked;
      assertTrue(vector.rustValidate(), vector.id() + " validate cannot see a wire-only mask defect");
      assertFalse(vector.rustDeserialize(), vector.id());
      assertEquals("InvalidValue", vector.rustDeserializeError(), vector.id());
      final var failure = assertThrows(
          IllegalStateException.class,
          () -> TransactionSkeleton.deserializeSkeleton(vector.wire()),
          vector.id()
      );
      assertEquals(
          "Both v1 priority fee TransactionConfigMask bits must be set: 0x" + Long.toHexString(vector.configMask()),
          failure.getMessage()
      );
    }
    assertEquals(2, checked, "half-set priority fee mask vectors");
  }

  /// DIVERGENCE, pinned rather than fixed. Rust's reader rejects any mask carrying a bit outside
  /// `KNOWN_BITS = 0b11111` with `InvalidValue`, before it reads anything else. Sava enforces only
  /// the priority-fee half of that check and then sizes the config block as four bytes per set bit
  /// "including unknown bits", so it accepts the message and allots a phantom four byte slot to the
  /// unknown bit. Everything after the config block is then shifted by four bytes.
  ///
  /// The raw-byte signing path is safe: `requireSignatureBlockOffset` refuses the corroboration, so
  /// `Transaction.getId`/`sign` cannot be pointed at the wrong 64 bytes. Only `deserializeSkeleton`
  /// is permissive, and the resulting view is wrong rather than merely unvalidated — a future
  /// SIMD bit that is not four bytes wide would mis-slice every field after it. Tightening Sava is
  /// a deliberate decision; this test pins Rust's side and Sava's current side either way.
  @Test
  void v1UnknownConfigMaskBitsAreRejectedAsRustRejectsThem() throws IOException {
    int checked = 0;
    for (final var vector : loadFixture().vectors()) {
      if (!vector.id().startsWith("reject_config_mask_unknown_")) {
        continue;
      }
      ++checked;
      final var id = vector.id();
      // Rust's validate() passes — the mask is structurally fine — and its reader is what refuses
      // the bytes, so the disagreement was only ever visible on the deserialize side.
      assertTrue(vector.rustValidate(), id);
      assertFalse(vector.rustDeserialize(), id + " Rust rejects unknown mask bits");
      assertEquals("InvalidValue", vector.rustDeserializeError(), id);
      assertEquals(1, Long.bitCount(vector.configMask() & ~0b11111L), id);

      // Sava now refuses them too. It has to: the ConfigValues block is sized from the mask, so a
      // slot allocated for a bit whose width this release cannot know shifts the instruction
      // headers and everything after them, and Sava would read the fixed width header out of
      // payload bytes. That is a plausible-looking wrong view, which deserialize exists to refuse.
      final byte[] wire = vector.wire();
      final var thrown = assertThrowsExactly(
          IllegalStateException.class,
          () -> TransactionSkeleton.deserializeSkeleton(wire),
          id
      );
      assertEquals(
          "Unknown v1 TransactionConfigMask bits: 0x" + Long.toHexString(vector.configMask()),
          thrown.getMessage(),
          id
      );
    }
    assertEquals(2, checked, "unknown config mask bit vectors");
  }

  /// Population limits are where Sava is deliberately permissive: too many signatures, addresses,
  /// or instructions leaves parsing meaningful, so the bytes stay readable for analysis and the
  /// limits are reported by the published `exceeds*` predicates instead of thrown from the reader.
  /// Rust's `validate()` rejects them with `TooManySignatures`, `TooManyAddresses`, and
  /// `TooManyInstructions`; the fixture pairs each with an accepted boundary vector.
  @Test
  void v1PopulationLimitsAreReportedRatherThanRejected() throws IOException {
    final var vectors = loadFixture().vectors();

    assertLimit(vectors, "accept_signatures_12", "reject_signatures_13", "TooManySignatures", Transaction::exceedsSignatureLimit);
    assertLimit(vectors, "accept_addresses_64", "reject_addresses_65", "TooManyAddresses", Transaction::exceedsAccountLimit);
    assertLimit(vectors, "accept_instructions_64", "reject_instructions_65", "TooManyInstructions", Transaction::exceedsInstructionLimit);
  }

  /// Rust's `validate()` requires a heap request to be a 1KiB multiple within [32KiB, 256KiB]. The
  /// skeleton reports whatever the wire carries — it is a reader — while the builder enforces the
  /// rule in strict mode, so both halves are pinned against the same Rust vectors.
  @Test
  void v1HeapSizeRuleMatchesRustValidateInTheBuilder() throws IOException {
    int checked = 0;
    for (final var vector : loadFixture().vectors()) {
      if (!vector.id().contains("heap_size")) {
        continue;
      }
      ++checked;
      final var id = vector.id();
      final int heapSize = (int) vector.configValues().get(HEAP_SIZE).value();
      final var skeleton = TransactionSkeleton.deserializeSkeleton(vector.wire());
      assertEquals(heapSize, skeleton.heapSize(), id + " the reader reports the wire value verbatim");

      if (vector.rustValidate()) {
        assertEquals("", vector.rustValidateError(), id);
        assertDoesNotThrow(() -> TxBuilder.createBuilder().heapSize(heapSize), id);
      } else {
        assertEquals("InvalidHeapSize", vector.rustValidateError(), id);
        assertThrows(IllegalArgumentException.class, () -> TxBuilder.createBuilder().heapSize(heapSize), id);
      }
    }
    assertEquals(5, checked, "heap size vectors");
  }

  /// Rust's `validate()` rejects a `program_id_index` of zero — the fee payer is never a program —
  /// with `InvalidInstructionAccountIndex`. Sava reads it: the index is in range, so the view is
  /// faithful, merely not executable. Pinned as current behaviour, not endorsed as correct bytes.
  @Test
  void v1FeePayerAsProgramIdIsReadableButInvalidToRust() throws IOException {
    final var vector = vector(loadFixture().vectors(), "reject_program_id_index_is_fee_payer");
    assertFalse(vector.rustValidate());
    assertEquals("InvalidInstructionAccountIndex", vector.rustValidateError());
    assertTrue(vector.rustDeserialize(), "the bytes still deserialize and round trip");

    final var skeleton = assertDoesNotThrow(() -> TransactionSkeleton.deserializeSkeleton(vector.wire()));
    assertEquals(0, vector.wire()[skeleton.instructionsOffset()] & 0xFF, "program id index");
    assertEquals(skeleton.feePayer(), skeleton.parseProgramAccounts()[0], "Sava reads the fee payer as the program");
  }

  /// DIVERGENCE, pinned rather than fixed. Rust's `validate()` rejects an instruction account index
  /// outside the address array with `InvalidInstructionAccountIndex`. Sava's reader is permissive
  /// and hands back a **null** element inside the instruction's `List<AccountMeta>` rather than
  /// throwing or omitting it, which is a footgun for every consumer that iterates the list.
  @Test
  void v1OutOfRangeInstructionAccountIndexIsRejected() throws IOException {
    final var vector = vector(loadFixture().vectors(), "reject_account_index_out_of_bounds");
    assertFalse(vector.rustValidate());
    assertEquals("InvalidInstructionAccountIndex", vector.rustValidateError());

    // The message still parses — the corruption is inside an instruction payload, not the framing.
    final var skeleton = assertDoesNotThrow(() -> TransactionSkeleton.deserializeSkeleton(vector.wire()));
    assertEquals(2, skeleton.numIncludedAccounts());
    final var accounts = skeleton.parseAccounts();
    final int payloadOffset = vector.offsets().get("instruction_payloads");
    assertEquals(0, vector.wire()[payloadOffset] & 0xFF);
    assertEquals(2, vector.wire()[payloadOffset + 1] & 0xFF, "the second index is past the last address");

    // Reading the instructions is where it is refused, matching Rust's InvalidInstructionAccountIndex
    // rather than substituting a null meta the caller would trip over later. Legacy and v0 still
    // substitute the null — see sava#57; v1 is new, so it does not inherit that.
    assertEquals(
        "Instruction account index 2 is outside the 2 accounts of this transaction.",
        assertThrowsExactly(
            IndexOutOfBoundsException.class,
            () -> skeleton.parseInstructions(accounts)
        ).getMessage()
    );
  }

  /// Every rejection vector must actually be a rejection somewhere in Rust, and every non-rejection
  /// vector must be clean. Guards the fixture against a regeneration that quietly turns a rejection
  /// row into an accepted one.
  @Test
  void everyRejectionVectorIsRejectedBySomeRustCheck() throws IOException {
    int rejections = 0;
    for (final var vector : loadFixture().vectors()) {
      final boolean rejected = !vector.rustValidate() || !vector.rustDeserialize();
      assertFalse(
          vector.rustDeserializeWithPrefix(),
          vector.id() + " v1::deserialize never consumes the 0x81 prefix"
      );
      if (vector.id().startsWith("reject_")) {
        ++rejections;
        assertTrue(rejected, vector.id() + " must be rejected by Rust");
      } else {
        assertFalse(rejected, vector.id() + " must be accepted by Rust");
        assertTrue(vector.rustWireRoundTrip(), vector.id());
        assertEquals("", vector.rustValidateError(), vector.id());
        assertEquals("", vector.rustDeserializeError(), vector.id());
      }
    }
    assertEquals(14, rejections, "rejection vectors");
  }

  private static void assertLimit(final List<Vector> vectors,
                                  final String acceptedId,
                                  final String rejectedId,
                                  final String rustError,
                                  final java.util.function.Predicate<Transaction> exceeds) {
    final var accepted = vector(vectors, acceptedId);
    assertTrue(accepted.rustValidate(), acceptedId);
    assertFalse(
        exceeds.test(TransactionSkeleton.deserializeSkeleton(accepted.wire()).createTransaction()),
        acceptedId + " is the accepted boundary"
    );

    final var rejected = vector(vectors, rejectedId);
    assertFalse(rejected.rustValidate(), rejectedId);
    assertEquals(rustError, rejected.rustValidateError(), rejectedId);
    assertTrue(rejected.rustDeserialize(), rejectedId + " still deserializes as bytes");
    final var transaction = assertDoesNotThrow(
        () -> TransactionSkeleton.deserializeSkeleton(rejected.wire()).createTransaction(),
        rejectedId + " remains readable and constructible for analysis"
    );
    assertTrue(exceeds.test(transaction), rejectedId + " is reported by the published limit predicate");
  }

  private static void assertConfigValue(final Vector vector,
                                        final byte[] wire,
                                        final String name,
                                        final int maskBits,
                                        final long savaValue) {
    final var expected = vector.configValues().get(name);
    final int offset = V1TransactionSkeleton.configValueOffset(wire, maskBits);
    if (expected == null) {
      assertEquals(-1, offset, vector.id() + " " + name + " must be absent");
      assertEquals(0L, savaValue, vector.id() + " an absent " + name + " reads as 0, not a runtime default");
      return;
    }
    assertEquals(expected.offset(), offset, vector.id() + " " + name + " offset");
    assertEquals(expected.value(), savaValue, vector.id() + " " + name + " value");
    final long onTheWire = name.equals(PRIORITY_FEE)
        ? ByteUtil.getInt64LE(wire, offset)
        : Integer.toUnsignedLong(ByteUtil.getInt32LE(wire, offset));
    assertEquals(expected.value(), onTheWire, vector.id() + " " + name + " wire bytes");
  }

  private static void assertInstructionsMatchRust(final Vector vector, final TransactionSkeleton skeleton) {
    if (vector.instructions().isEmpty()) {
      return;
    }
    final var id = vector.id();
    final var accounts = skeleton.parseAccounts();
    final var instructions = skeleton.parseInstructions(accounts);
    assertEquals(vector.instructions().size(), instructions.length, id + " instruction count");
    final var withoutAccounts = skeleton.parseInstructionsWithoutAccounts();
    final var programs = skeleton.parseProgramAccounts();
    for (int index = 0; index < instructions.length; ++index) {
      final var expected = vector.instructions().get(index);
      final var actual = instructions[index];
      assertArrayEquals(expected.program(), actual.programId().publicKey().toByteArray(), id + " program " + index);
      assertArrayEquals(expected.program(), programs[index].toByteArray(), id + " program account " + index);
      assertArrayEquals(expected.data(), actual.copyData(), id + " data " + index);
      assertArrayEquals(expected.data(), withoutAccounts[index].copyData(), id + " data without accounts " + index);
      assertEquals(expected.accounts().size(), actual.accounts().size(), id + " instruction " + index + " accounts");
      for (int a = 0; a < expected.accounts().size(); ++a) {
        assertArrayEquals(
            expected.accounts().get(a).key(),
            actual.accounts().get(a).publicKey().toByteArray(),
            id + " instruction " + index + " account " + a
        );
      }
    }
  }

  /// Whether Rust and Sava both accept the bytes and agree on where every field starts. Excludes
  /// the four byte-patched mask vectors, which Rust rejects outright, and the two header vectors
  /// Sava rejects because they partition the address array wrongly.
  private static boolean savaAgreesOnLayout(final Vector vector) {
    return vector.rustDeserialize()
        && vector.numReadonlySigned() < vector.numRequiredSignatures()
        && vector.numAddresses() >= vector.numRequiredSignatures() + vector.numReadonlyUnsigned();
  }

  private static Vector vector(final List<Vector> vectors, final String id) {
    return vectors.stream()
        .filter(candidate -> candidate.id().equals(id))
        .findFirst()
        .orElseThrow(() -> new AssertionError("missing fixture vector " + id));
  }

  private static Fixture loadFixture() throws IOException {
    final var input = V1MessageConformanceTests.class.getResourceAsStream(RESOURCE);
    assertNotNull(input, "missing fixture " + RESOURCE);
    final var metadata = new LinkedHashMap<String, String>();
    final var vectors = new ArrayList<Vector>();
    boolean sawColumns = false;
    try (var reader = new BufferedReader(new InputStreamReader(input, StandardCharsets.UTF_8))) {
      String line;
      int lineNumber = 0;
      while ((line = reader.readLine()) != null) {
        ++lineNumber;
        final int currentLine = lineNumber;
        assertFalse(line.isBlank(), () -> "blank fixture line " + currentLine);
        if (line.startsWith("# ")) {
          assertFalse(sawColumns, () -> "metadata after columns at " + currentLine);
          final int separator = line.indexOf(": ", 2);
          assertTrue(separator > 2, () -> "malformed metadata at " + currentLine);
          final String key = line.substring(2, separator);
          assertNull(metadata.putIfAbsent(key, line.substring(separator + 2)), () -> "duplicate " + key);
        } else if (!sawColumns) {
          assertEquals(COLUMNS, line, () -> "columns at " + currentLine);
          sawColumns = true;
        } else {
          vectors.add(parseVector(line, currentLine));
        }
      }
    }
    assertTrue(sawColumns, "missing columns");
    assertEquals(EXPECTED_METADATA, metadata, "fixture provenance changed");
    assertEquals(VECTOR_COUNT, vectors.size());
    return new Fixture(metadata, vectors);
  }

  private static Vector parseVector(final String line, final int lineNumber) {
    final String[] fields = line.split("\\t", -1);
    assertEquals(22, fields.length, () -> "field count at " + lineNumber);
    final String[] header = fields[2].split(":", -1);
    assertEquals(3, header.length, () -> "header at " + lineNumber);
    return new Vector(
        fields[0],
        fields[1],
        Integer.parseInt(header[0]),
        Integer.parseInt(header[1]),
        Integer.parseInt(header[2]),
        Long.parseLong(fields[3]),
        Integer.parseInt(fields[4]),
        Integer.parseInt(fields[5]),
        Integer.parseInt(fields[6]),
        parseOffsets(fields[7], lineNumber),
        parseConfigValues(fields[8], lineNumber),
        HEX.parseHex(fields[9]),
        parseByteArrays(fields[10]),
        parseInstructions(fields[11]),
        parseByteArrays(fields[12]),
        parseByteArrays(fields[13]),
        Integer.parseInt(fields[14]),
        HEX.parseHex(fields[15]),
        // The two error columns sit beside the boolean they explain, so the last column is always
        // populated and the fixture carries no trailing tab. The record's field order is unchanged.
        parseBoolean(fields[16], lineNumber),
        parseBoolean(fields[18], lineNumber),
        parseBoolean(fields[20], lineNumber),
        parseBoolean(fields[21], lineNumber),
        fields[17],
        fields[19]
    );
  }

  private static Map<String, Integer> parseOffsets(final String encoded, final int lineNumber) {
    final var offsets = new LinkedHashMap<String, Integer>();
    for (final var entry : encoded.split(";", -1)) {
      final int separator = entry.indexOf('=');
      assertTrue(separator > 0, () -> "offset entry at " + lineNumber);
      offsets.put(entry.substring(0, separator), Integer.parseInt(entry.substring(separator + 1)));
    }
    assertEquals(
        List.of(
            "version", "header", "config_mask", "lifetime_specifier", "num_instructions",
            "num_addresses", "addresses", "config_values", "instruction_headers",
            "instruction_payloads", "message_end"
        ),
        List.copyOf(offsets.keySet()),
        () -> "offset names at " + lineNumber
    );
    return offsets;
  }

  private static Map<String, ConfigValue> parseConfigValues(final String encoded, final int lineNumber) {
    if (encoded.isEmpty()) {
      return Map.of();
    }
    final var configValues = new LinkedHashMap<String, ConfigValue>();
    for (final var entry : encoded.split(";", -1)) {
      final int at = entry.indexOf('@');
      final int equals = entry.indexOf('=', at);
      assertTrue(at > 0 && equals > at, () -> "config value entry at " + lineNumber);
      configValues.put(
          entry.substring(0, at),
          new ConfigValue(
              Integer.parseInt(entry.substring(at + 1, equals)),
              Long.parseLong(entry.substring(equals + 1))
          )
      );
    }
    return configValues;
  }

  private static List<IxSpec> parseInstructions(final String encoded) {
    if (encoded.isEmpty()) {
      return List.of();
    }
    final var instructions = new ArrayList<IxSpec>();
    for (final var encodedInstruction : encoded.split(";", -1)) {
      final String[] fields = encodedInstruction.split("\\|", -1);
      assertEquals(3, fields.length, () -> "instruction fields in " + encodedInstruction);
      final var accounts = new ArrayList<MetaSpec>();
      if (!fields[1].isEmpty()) {
        for (final var encodedMeta : fields[1].split(",", -1)) {
          final String[] meta = encodedMeta.split(":", -1);
          assertEquals(3, meta.length, () -> "meta fields in " + encodedMeta);
          accounts.add(new MetaSpec(HEX.parseHex(meta[0]), meta[1].equals("1"), meta[2].equals("1")));
        }
      }
      instructions.add(new IxSpec(HEX.parseHex(fields[0]), accounts, HEX.parseHex(fields[2])));
    }
    return instructions;
  }

  private static List<byte[]> parseByteArrays(final String encoded) {
    if (encoded.isEmpty()) {
      return List.of();
    }
    return Arrays.stream(encoded.split(",", -1)).map(HEX::parseHex).toList();
  }

  private static boolean parseBoolean(final String value, final int lineNumber) {
    assertTrue(value.equals("true") || value.equals("false"), () -> "boolean at " + lineNumber);
    return Boolean.parseBoolean(value);
  }

  private static void assertFileSha256(final Map<String, String> metadata,
                                       final String metadataKey,
                                       final String relativePath) throws IOException {
    final var path = generatorPath(relativePath);
    assertEquals(
        metadata.get(metadataKey),
        HEX.formatHex(sha256().digest(Files.readAllBytes(path))),
        () -> "stale fixture provenance for " + path
    );
  }

  private static Path generatorPath(final String relativePath) {
    final var moduleRelative = Path.of(GENERATOR).resolve(relativePath);
    if (Files.isRegularFile(moduleRelative)) {
      return moduleRelative;
    }
    final var repositoryRelative = Path.of("sava-core").resolve(moduleRelative);
    assertTrue(Files.isRegularFile(repositoryRelative), () -> "missing generator input " + relativePath);
    return repositoryRelative;
  }

  private static MessageDigest sha256() {
    try {
      return MessageDigest.getInstance("SHA-256");
    } catch (final NoSuchAlgorithmException e) {
      throw new AssertionError("JDK has no SHA-256 provider", e);
    }
  }

  private record Fixture(Map<String, String> metadata, List<Vector> vectors) {
  }

  private record Vector(
      String id,
      String category,
      int numRequiredSignatures,
      int numReadonlySigned,
      int numReadonlyUnsigned,
      long configMask,
      int numAddresses,
      int numInstructions,
      int messageLen,
      Map<String, Integer> offsets,
      Map<String, ConfigValue> configValues,
      byte[] message,
      List<byte[]> addresses,
      List<IxSpec> instructions,
      List<byte[]> signerSeeds,
      List<byte[]> signatures,
      int signatureBlockOffset,
      byte[] transaction,
      boolean rustValidate,
      boolean rustDeserialize,
      boolean rustDeserializeWithPrefix,
      boolean rustWireRoundTrip,
      String rustValidateError,
      String rustDeserializeError
  ) {

    /// The v1 transaction wire: the serialized message, then the signature block, with nothing
    /// between them. Unsigned vectors carry all-zero placeholder slots.
    byte[] wire() {
      final byte[] wire = new byte[messageLen + (signatures.size() * Transaction.SIGNATURE_LENGTH)];
      System.arraycopy(message, 0, wire, 0, message.length);
      int offset = messageLen;
      for (final var signature : signatures) {
        System.arraycopy(signature, 0, wire, offset, Transaction.SIGNATURE_LENGTH);
        offset += Transaction.SIGNATURE_LENGTH;
      }
      return wire;
    }
  }

  private record ConfigValue(int offset, long value) {
  }

  private record IxSpec(byte[] program, List<MetaSpec> accounts, byte[] data) {
  }

  private record MetaSpec(byte[] key, boolean signer, boolean writable) {
  }

  private record Role(boolean signer, boolean writable) {
  }
}
