package software.sava.core.tx;

import org.junit.jupiter.api.Test;
import software.sava.core.accounts.PublicKey;
import software.sava.core.encoding.ByteUtil;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static software.sava.core.tx.TxBuilderImpl.V1_INSTRUCTION_HEADER_LENGTH;
import static software.sava.core.tx.TxBuilderImpl.V1_VERSION_BYTE;
import static software.sava.core.tx.V1TransactionSkeleton.ACCOUNT_DATA_SIZE_LIMIT_MASK;
import static software.sava.core.tx.V1TransactionSkeleton.COMPUTE_UNIT_LIMIT_MASK;
import static software.sava.core.tx.V1TransactionSkeleton.HEAP_SIZE_MASK;
import static software.sava.core.tx.V1TransactionSkeleton.PRIORITY_FEE_MASK;
import static software.sava.core.tx.V1TransactionSkeleton.V1_ACCOUNTS_OFFSET;
import static software.sava.core.tx.V1TransactionSkeleton.V1_CONFIG_MASK_OFFSET;
import static software.sava.core.tx.V1TransactionSkeleton.V1_RECENT_BLOCK_HASH_INDEX;

/// The three UPSTREAM-AUTHORED SIMD-0385 wire vectors, transcribed byte for byte from
/// `anza-xyz/solana-sdk` (Apache-2.0, the same licence as Sava).
///
/// [V1MessageConformanceTests] already covers this layout far more broadly, from a committed
/// fixture generated by executing Rust. This file is not redundant with it, because the two answer
/// different questions. The generated fixture proves Sava agrees with a Rust program *Sava's own
/// generator wrote*: if the generator's driving code and Sava's reader share a misreading of the
/// SIMD — a field ordered wrongly, a mask bit given the wrong width, an offset counted from the
/// wrong side of the version byte — the generator emits bytes matching the misreading and Sava
/// parses them back happily. A self-generated oracle structurally cannot catch a mistake made on
/// both sides of it.
///
/// These three vectors were authored by the format's own maintainers, with their expected bytes
/// spelled out by hand in the upstream test rather than produced by any serializer, so they close
/// exactly that gap. They are few, and their inputs are deliberately trivial — that is the point:
/// what they pin is the *interpretation*, not the coverage.
///
/// Cited upstream locations are line numbers at the time of transcription; the test names are
/// stable and should be used to relocate them.
final class V1UpstreamVectorTests {

  private static final int BLOCK_HASH_LENGTH = Transaction.BLOCK_HASH_LENGTH;
  private static final int PUBLIC_KEY_LENGTH = PublicKey.PUBLIC_KEY_LENGTH;

  /// Rust's `Address::new_from_array([n; 32])` / `Hash::new_from_array([n; 32])`.
  private static byte[] repeated(final int value) {
    final byte[] bytes = new byte[PUBLIC_KEY_LENGTH];
    Arrays.fill(bytes, (byte) value);
    return bytes;
  }

  /// Both `byte_layout_*` vectors are the v1 MESSAGE BODY only, with no version byte: upstream's
  /// `wincode::serialize(&message)` serializes a `v1::Message`, and the `0x81` prefix is written one
  /// layer up by `VersionedMessage::serialize`
  /// (`message/src/versions/mod.rs:435`, `V1(message) => { … push(V1_MESSAGE_PREFIX) … }`).
  ///
  /// Sava has no separate message type: [V1TransactionSkeleton] is entered at the
  /// `VersionedTransaction` layer and counts the prefix in every offset it derives —
  /// [V1TransactionSkeleton#V1_CONFIG_MASK_OFFSET] is `1 + 3`, not `3`. So the prefix is prepended
  /// here, and **every Sava offset asserted below is exactly one greater than the corresponding
  /// offset within upstream's expected vector.** That single byte is the whole prefix boundary:
  /// upstream index `i` is Sava index `i + 1`, and upstream's message length is Sava's minus one.
  private static byte[] withVersionPrefix(final byte[] messageBody) {
    final byte[] message = new byte[1 + messageBody.length];
    message[0] = V1_VERSION_BYTE;
    System.arraycopy(messageBody, 0, message, 1, messageBody.length);
    return message;
  }

  /// A v1 transaction is the serialized message immediately followed by one 64 byte signature slot
  /// per `num_required_signatures`, with no count on the wire. Upstream's two byte-layout vectors
  /// stop at the message, and both declare one required signature, so one zeroed (unsigned) slot is
  /// appended to give Sava the full transaction its length-implied signature block check needs.
  private static byte[] withUnsignedSignatureBlock(final byte[] message) {
    return Arrays.copyOf(message, message.length + Transaction.SIGNATURE_LENGTH);
  }

  /// Upstream: `message/src/versions/v1/message.rs:1286`, `byte_layout_without_config`.
  ///
  /// Assembled in the same field order, with the same names, as upstream's `expected` vector so the
  /// two can be diffed line by line.
  @Test
  void byteLayoutWithoutConfig() {
    final byte[] feePayerAddress = repeated(0x01);
    final byte[] programAddress = repeated(0x02);
    final byte[] blockhash = repeated(0xAB);

    final var expected = ByteBuffer.allocate(112).order(ByteOrder.LITTLE_ENDIAN);
    expected.put((byte) 1); // num_required_signatures
    expected.put((byte) 0); // num_readonly_signed_accounts
    expected.put((byte) 0); // num_readonly_unsigned_accounts
    expected.putInt(0); // ConfigMask = 0
    expected.put(blockhash); // LifetimeSpecifier
    expected.put((byte) 1); // NumInstructions
    expected.put((byte) 2); // NumAddresses
    expected.put(feePayerAddress); // fee_payer
    expected.put(programAddress); // program
    // ConfigValues: none
    expected.put((byte) 1); // program_id_index
    expected.put((byte) 1); // num_accounts
    expected.putShort((short) 2); // data_len
    expected.put((byte) 0); // account index 0
    expected.put(new byte[]{(byte) 0xDE, (byte) 0xAD}); // data
    assertEquals(112, expected.position(), "upstream's expected vector is exactly 112 message bytes");

    final byte[] messageBody = expected.array();
    final byte[] message = withVersionPrefix(messageBody);
    final byte[] wire = withUnsignedSignatureBlock(message);
    assertEquals(113, message.length, "112 upstream message bytes plus the 0x81 prefix");

    final var skeleton = TransactionSkeleton.deserializeSkeleton(wire);
    assertInstanceOf(V1TransactionSkeleton.class, skeleton, "0x81 with a non-zero signature count dispatches to v1");
    assertTrue(V1Transaction.isV1(wire));
    assertTrue(skeleton.isVersioned());
    assertFalse(skeleton.isLegacy());
    assertEquals(1, skeleton.version());

    // LegacyHeader
    assertEquals(1, skeleton.numSignatures(), "num_required_signatures");
    assertEquals(0, skeleton.numReadonlySignedAccounts(), "num_readonly_signed_accounts");
    assertEquals(0, skeleton.numReadonlyUnsignedAccounts(), "num_readonly_unsigned_accounts");

    // ConfigMask = 0, so no ConfigValue is present and none of the four reads a byte of the
    // instruction block that follows the addresses directly.
    final var v1Skeleton = (V1TransactionSkeleton) skeleton;
    assertEquals(0, v1Skeleton.configMask(), "ConfigMask");
    assertEquals(0, ByteUtil.getInt32LE(wire, V1_CONFIG_MASK_OFFSET), "ConfigMask is a u32 LE at Sava offset 4, upstream offset 3");
    assertEquals(0L, v1Skeleton.priorityFeeLamports());
    assertEquals(0, v1Skeleton.computeUnitLimit());
    assertEquals(0, v1Skeleton.accountDataSizeLimit());
    assertEquals(0, v1Skeleton.heapSize());
    assertEquals(-1, V1TransactionSkeleton.configValueOffset(wire, PRIORITY_FEE_MASK));
    assertEquals(-1, V1TransactionSkeleton.configValueOffset(wire, COMPUTE_UNIT_LIMIT_MASK));
    assertEquals(-1, V1TransactionSkeleton.configValueOffset(wire, ACCOUNT_DATA_SIZE_LIMIT_MASK));
    assertEquals(-1, V1TransactionSkeleton.configValueOffset(wire, HEAP_SIZE_MASK));

    // LifetimeSpecifier: upstream offset 7, Sava offset 8.
    assertEquals(8, V1_RECENT_BLOCK_HASH_INDEX);
    assertEquals(V1_RECENT_BLOCK_HASH_INDEX, skeleton.recentBlockHashIndex());
    assertArrayEquals(blockhash, skeleton.blockHash(), "LifetimeSpecifier");
    assertArrayEquals(
        Arrays.copyOfRange(messageBody, 7, 7 + BLOCK_HASH_LENGTH),
        Arrays.copyOfRange(wire, V1_RECENT_BLOCK_HASH_INDEX, V1_RECENT_BLOCK_HASH_INDEX + BLOCK_HASH_LENGTH),
        "the prefix shifts the LifetimeSpecifier by exactly one byte"
    );

    // NumInstructions and NumAddresses, the two bytes immediately preceding the addresses.
    assertEquals(1, skeleton.numInstructions(), "NumInstructions");
    assertEquals(2, skeleton.numIncludedAccounts(), "NumAddresses");
    assertEquals(2, skeleton.numAccounts());
    assertEquals(0, skeleton.numIndexedAccounts(), "v1 loads no address lookup table accounts");
    assertEquals(0, skeleton.lookupTableAccounts().length);
    assertEquals(1, wire[V1_ACCOUNTS_OFFSET - 2] & 0xFF, "NumInstructions at Sava offset 40, upstream offset 39");
    assertEquals(2, wire[V1_ACCOUNTS_OFFSET - 1] & 0xFF, "NumAddresses at Sava offset 41, upstream offset 40");

    // Addresses: fee_payer then program, at Sava offset 42, upstream offset 41.
    assertEquals(42, V1_ACCOUNTS_OFFSET);
    final var accounts = skeleton.parseAccounts();
    assertEquals(2, accounts.length);
    assertArrayEquals(feePayerAddress, accounts[0].publicKey().toByteArray(), "fee_payer");
    assertArrayEquals(feePayerAddress, skeleton.feePayer().toByteArray(), "fee_payer is the first address");
    assertTrue(accounts[0].feePayer());
    assertTrue(accounts[0].signer());
    assertTrue(accounts[0].write());
    assertArrayEquals(programAddress, accounts[1].publicKey().toByteArray(), "program");
    assertFalse(accounts[1].signer(), "one required signature, so only the fee payer signs");

    // InstructionHeader: (u8 program_id_index, u8 num_accounts, u16 LE data_len), immediately after
    // the addresses because the ConfigValues block is empty.
    final int instructionsOffset = V1_ACCOUNTS_OFFSET + (2 * PUBLIC_KEY_LENGTH);
    assertEquals(106, instructionsOffset, "upstream writes the instruction header at offset 105");
    assertEquals(instructionsOffset, skeleton.instructionsOffset());
    assertEquals(1, wire[instructionsOffset] & 0xFF, "program_id_index");
    assertEquals(1, wire[instructionsOffset + 1] & 0xFF, "num_accounts");
    assertEquals(2, ByteUtil.getInt16LE(wire, instructionsOffset + 2) & 0xFFFF, "data_len");

    final var instructions = skeleton.parseInstructions(accounts);
    assertEquals(1, instructions.length);
    final var instruction = instructions[0];
    assertArrayEquals(programAddress, instruction.programId().publicKey().toByteArray(), "program_id_index 1 resolves to the program address");
    assertTrue(instruction.programId().invoked());
    assertEquals(1, instruction.accounts().size(), "num_accounts");
    assertArrayEquals(feePayerAddress, instruction.accounts().getFirst().publicKey().toByteArray(), "account index 0");
    assertArrayEquals(new byte[]{(byte) 0xDE, (byte) 0xAD}, instruction.copyData(), "data");

    // The whole message: the header block plus the one payload lands on upstream's 112 bytes,
    // which is where the appended signature block has to begin.
    assertEquals(
        V1_INSTRUCTION_HEADER_LENGTH + 1 + 2,
        skeleton.serializedInstructionsLength(),
        "one 4 byte header, one account index, two data bytes"
    );
    assertEquals(113, instructionsOffset + skeleton.serializedInstructionsLength(), "112 upstream bytes plus the prefix");
    assertEquals(113, V1TransactionSkeleton.messageEnd(wire));
    assertEquals(113, V1TransactionSkeleton.requireSignatureBlockOffset(wire));
    assertArrayEquals(message, Arrays.copyOf(wire, 113), "the message precedes the signature block byte for byte");

    // The parse round trips: rebuilding from the skeleton reproduces upstream's bytes exactly.
    assertArrayEquals(wire, skeleton.createTransaction().serialized());
  }

  /// Upstream: `message/src/versions/v1/message.rs:1327`, `byte_layout_with_config`.
  ///
  /// The priority fee is a `u64` behind the two-bit mask pair, and the compute unit limit a `u32`
  /// behind one bit; reading the pair as a single four-byte slot misplaces the limit and everything
  /// after it, which is what this vector's mixed config block pins.
  @Test
  void byteLayoutWithConfig() {
    final byte[] feePayerAddress = repeated(0x01);
    final byte[] programAddress = repeated(0x02);
    final byte[] blockhash = repeated(0xBB);
    final long priorityFee = 0x0102030405060708L;
    final int computeUnitLimit = 0x11223344;

    final var expected = ByteBuffer.allocate(121).order(ByteOrder.LITTLE_ENDIAN);
    expected.put((byte) 1); // num_required_signatures
    expected.put((byte) 0); // num_readonly_signed_accounts
    expected.put((byte) 0); // num_readonly_unsigned_accounts
    // ConfigMask: priority fee (bits 0,1) + CU limit (bit 2) = 0b111 = 7
    expected.putInt(7);
    expected.put(blockhash); // LifetimeSpecifier
    expected.put((byte) 1); // NumInstructions
    expected.put((byte) 2); // NumAddresses
    expected.put(feePayerAddress); // fee_payer
    expected.put(programAddress); // program
    expected.putLong(priorityFee); // Priority fee as u64 LE
    expected.putInt(computeUnitLimit); // Compute unit limit as u32 LE
    expected.put((byte) 1); // program_id_index
    expected.put((byte) 0); // num_accounts
    expected.putShort((short) 0); // data_len
    assertEquals(121, expected.position(), "upstream's expected vector is exactly 121 message bytes");

    final byte[] messageBody = expected.array();
    final byte[] message = withVersionPrefix(messageBody);
    final byte[] wire = withUnsignedSignatureBlock(message);
    assertEquals(122, message.length, "121 upstream message bytes plus the 0x81 prefix");

    final var skeleton = (V1TransactionSkeleton) TransactionSkeleton.deserializeSkeleton(wire);
    assertEquals(1, skeleton.numSignatures(), "num_required_signatures");
    assertEquals(0, skeleton.numReadonlySignedAccounts(), "num_readonly_signed_accounts");
    assertEquals(0, skeleton.numReadonlyUnsignedAccounts(), "num_readonly_unsigned_accounts");
    assertArrayEquals(blockhash, skeleton.blockHash(), "LifetimeSpecifier");
    assertEquals(1, skeleton.numInstructions(), "NumInstructions");
    assertEquals(2, skeleton.numIncludedAccounts(), "NumAddresses");
    assertArrayEquals(feePayerAddress, skeleton.feePayer().toByteArray(), "fee_payer");

    // ConfigMask = 7: both priority fee bits and the compute unit limit bit.
    assertEquals(7, skeleton.configMask(), "ConfigMask");
    assertEquals(7, ByteUtil.getInt32LE(wire, V1_CONFIG_MASK_OFFSET), "ConfigMask is a u32 LE at Sava offset 4, upstream offset 3");
    assertEquals(PRIORITY_FEE_MASK | COMPUTE_UNIT_LIMIT_MASK, skeleton.configMask());

    // ConfigValues begin where the addresses end: Sava offset 106, upstream offset 105.
    final int configValuesOffset = V1_ACCOUNTS_OFFSET + (2 * PUBLIC_KEY_LENGTH);
    assertEquals(106, configValuesOffset, "upstream writes the priority fee at offset 105");
    assertEquals(configValuesOffset, V1TransactionSkeleton.configValueOffset(wire, PRIORITY_FEE_MASK), "priority fee sorts first");
    assertEquals(priorityFee, skeleton.priorityFeeLamports(), "Priority fee as u64 LE");
    assertEquals(priorityFee, ByteUtil.getInt64LE(wire, configValuesOffset));

    // The u64 fee occupies both of its mask bits' four-byte slots, so the limit follows eight bytes
    // later, at Sava offset 114 and upstream offset 113.
    final int computeUnitLimitOffset = configValuesOffset + Long.BYTES;
    assertEquals(114, computeUnitLimitOffset, "upstream writes the compute unit limit at offset 113");
    assertEquals(computeUnitLimitOffset, V1TransactionSkeleton.configValueOffset(wire, COMPUTE_UNIT_LIMIT_MASK));
    assertEquals(computeUnitLimit, skeleton.computeUnitLimit(), "Compute unit limit as u32 LE");
    assertEquals(computeUnitLimit, ByteUtil.getInt32LE(wire, computeUnitLimitOffset));

    // The two unset config bits read as absent rather than as whatever follows them on the wire.
    assertEquals(-1, V1TransactionSkeleton.configValueOffset(wire, ACCOUNT_DATA_SIZE_LIMIT_MASK));
    assertEquals(-1, V1TransactionSkeleton.configValueOffset(wire, HEAP_SIZE_MASK));
    assertEquals(0, skeleton.accountDataSizeLimit());
    assertEquals(0, skeleton.heapSize());

    // The instruction header follows the twelve config bytes: Sava offset 118, upstream offset 117.
    final int instructionsOffset = computeUnitLimitOffset + Integer.BYTES;
    assertEquals(118, instructionsOffset, "upstream writes the instruction header at offset 117");
    assertEquals(instructionsOffset, skeleton.instructionsOffset());
    assertEquals(1, wire[instructionsOffset] & 0xFF, "program_id_index");
    assertEquals(0, wire[instructionsOffset + 1] & 0xFF, "num_accounts");
    assertEquals(0, ByteUtil.getInt16LE(wire, instructionsOffset + 2) & 0xFFFF, "data_len");

    final var instructions = skeleton.parseInstructions(skeleton.parseAccounts());
    assertEquals(1, instructions.length);
    assertArrayEquals(programAddress, instructions[0].programId().publicKey().toByteArray(), "program_id_index 1 resolves to the program address");
    assertTrue(instructions[0].accounts().isEmpty(), "num_accounts");
    assertEquals(0, instructions[0].len(), "data_len");

    // An empty instruction payload, so the message ends at the last header byte.
    assertEquals(V1_INSTRUCTION_HEADER_LENGTH, skeleton.serializedInstructionsLength());
    assertEquals(122, instructionsOffset + skeleton.serializedInstructionsLength(), "121 upstream bytes plus the prefix");
    assertEquals(122, V1TransactionSkeleton.messageEnd(wire));
    assertEquals(122, V1TransactionSkeleton.requireSignatureBlockOffset(wire));
    assertArrayEquals(message, Arrays.copyOf(wire, 122), "the message precedes the signature block byte for byte");

    assertArrayEquals(wire, skeleton.createTransaction().serialized());
  }

  /// Upstream: `transaction/src/versioned/mod.rs:860`, `test_v1_message_in_legacy_transaction`.
  ///
  /// A v1 message body wrapped in the LEGACY envelope: a compact-u16 signature count of zero, then
  /// the `0x81` prefix and a complete v1 message. Upstream's `wincode::deserialize` takes the
  /// legacy/v0 path on the leading zero, then rejects `0x81` as a message version with
  /// `ReadError::Custom("invalid message version")`.
  ///
  /// Sava's v1 discriminator is `data[0] == 0x81 && data[1] != 0` — [SigningCountTests]
  /// (`bothHalvesOfTheV1DiscriminatorAreRequired`) covers why both halves are needed, including the
  /// non-canonical `0x81 0x00` legacy prefix that leads with the same version byte. This test does
  /// not restate that; it pins Sava's behaviour on upstream's exact 75 bytes, which sit on the other
  /// side of the same fork: `data[0]` is `0x00`, so nothing about them looks like v1 to Sava at all.
  ///
  /// **Sava does not agree with upstream here, deliberately.** A `TransactionSkeleton` is a
  /// permissive byte-oriented reader, so the legacy walk parses these bytes into a structurally
  /// meaningless but faithful view instead of refusing them: the `0x81` is consumed as a versioned
  /// message's version byte, masked to version 1, and the four ConfigMask bytes that follow the v1
  /// header are read as a legacy account count and the start of the blockhash. Nothing is
  /// misattributed — the view simply describes bytes that no cluster would accept. Sava refuses at
  /// the point where refusal matters, building a signable transaction, because the envelope's zero
  /// signature slots cannot satisfy the one signature the header inside declares.
  @Test
  void v1MessageInsideALegacyEnvelopeIsNotReadAsV1() {
    final byte[] malformedInput = {
        0x00,                   // 0 signatures via ShortU16 -> takes Legacy/V0 path
        (byte) 0x81,            // V1 message prefix
        // V1 LegacyHeader (3 bytes)
        0x01,                   // num_required_signatures = 1
        0x00,                   // num_readonly_signed_accounts = 0
        0x00,                   // num_readonly_unsigned_accounts = 0
        // TransactionConfigMask (4 bytes, little-endian)
        0x00, 0x00, 0x00, 0x00,
        // LifetimeSpecifier / blockhash (32 bytes)
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        // NumInstructions (1 byte)
        0x00,
        // NumAddresses (1 byte)
        0x01,
        // 1 address (32 bytes)
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    };
    assertEquals(75, malformedInput.length, "1 count byte, the 0x81 prefix and a 73 byte v1 message");

    // The leading zero is a legacy signature count, so the v1 discriminator never fires.
    assertFalse(V1Transaction.isV1(malformedInput));
    final var skeleton = TransactionSkeleton.deserializeSkeleton(malformedInput);
    assertFalse(skeleton instanceof V1TransactionSkeleton, "the legacy walk owns these bytes, not the v1 skeleton");
    assertInstanceOf(TransactionSkeletonImpl.class, skeleton);

    // What the legacy walk makes of a v1 body: 0x81 masked to version 1, then the v1 ConfigMask's
    // first byte read as the compact-u16 address count.
    assertEquals(1, skeleton.version(), "0x81 & 0x7F");
    assertTrue(skeleton.isVersioned());
    assertEquals(1, skeleton.numSignatures(), "the v1 header's num_required_signatures");
    assertEquals(0, skeleton.numIncludedAccounts(), "the ConfigMask's first byte, read as an account count");
    assertEquals(0, skeleton.numInstructions());

    // Rejected where it counts: the envelope carries no signature slots at all, so there is nowhere
    // to put the one signature the message header requires.
    final var thrown = assertThrows(IllegalStateException.class, () -> skeleton.createTransaction(List.of()));
    assertEquals(
        "Serialized signature count 0 does not match the message header's required signature count 1.",
        thrown.getMessage()
    );
  }
}
