name: Gradle Check

on:
  push:
    branches:
      - main

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    uses: sava-software/sava-build/.github/workflows/build.yml@main
    secrets: inherit
